### ISSUE TITLE
dataType: "decimal" gives a string through the api

### ISSUE THREAD

**Issue by jlvdh** [strongloop/loopback-connector-postgresql#101]
When using dataType: decimal the api seems to return a string instead of a number.

in model.json:

```
"property1": {
  "type": "number",
  "postgresql": {
    "dataType": "decimal"
  }
"property2": {
  "type": "number"
}
```

from the api:

```
"property1": "30.3",
 "property2": 4
```

**Comment by raymondfeng** [comment]
Do you see it from REST or node?

**Comment by jlvdh** [comment]
from the loopback explorer

**Comment by raymondfeng** [comment]
This is the behavior from the postgresql node.js driver - https://github.com/brianc/node-postgres/pull/353. The main purpose is to avoid loss of decimal data.

**Comment by jlvdh** [comment]
Thanks, that's clarifying a lot.

However, I'm running in to trouble while using the validatesNumericalityOf when doing a put request changing only another property.

    PUT /api/model/4

    { "other_property": "other value" }

gives:

    "message": "The `model` instance is not valid. Details: `property1` is not a number (value: \"3000\").",

**Comment by mirek** [comment]
@jlvdh if you don't care about decimal precision or you can guarantee safe precision (21?) you can do something like https://github.com/mirek/node-pg-safe-numbers is doing, but it's global/intrusive on pg, so care must be taken (all other libraries using pg will also use new parser).

**Comment by FreakTheMighty** [comment]
This confused me as well. Also, it seems a little inconsistent. On a PUT I found that the response was a number. When listing the resource, however, it has been converted to a string.

**Comment by ssh24** [comment]
Related to https://github.com/strongloop/loopback-connector-postgresql/issues/58. Closing this issue. Feel free to reopen if needed.
