### ISSUE TITLE
relation are not created

### ISSUE THREAD

**Issue by ezraroi** [strongloop/loopback-connector-postgresql#102]
Hi,
I have model that is defined with a relation:

```javascript
{
  "name": "comment",
  "plural": "comments",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true,
      "postgresql": {
          "schema": "public",
          "table": "comments"
      }
  },
  "properties": {
    "creationTime": {
      "type": "date",
      "default": "$now",
        "postgresql": {
            "columnName": "creationTime",
            "dataType": "TIMESTAMP WITH TIME ZONE",
            "nullable": "NO"
        }
    },
    "text": {
      "type": "string",
        "postgresql": {
            "columnName": "text",
            "dataType": "character varying",
            "dataPrecision": null,
            "dataScale": null,
            "dataLength": 1024,
            "nullable": "NO"
        }
    }
  },
  "validations": [],
  "relations": {
    "creator": {
      "type": "belongsTo",
      "model": "shutdownUser",
      "foreignKey": "creatorId"
    }
  },
  "acls": [],
  "methods": []
}
```

When i am running my application I am getting the following error:
uncaughtException: relation "public.shutdownUsers" does not exist

Who is in charge of the relation table creation?

**Comment by ezraroi** [comment]
Was an error in the automigrate script

**Comment by faustomorales** [comment]
How did you do this? Right now, I'm running this script but I'm the relation tables are not getting created.

````
var server = require('./server/server');
var ds = server.dataSources.db;
var lbTables = ['AccessToken', 'ACL', 'RoleMapping', 'Role', 'audience', 'comment', 'location', 'resource', 'type', 'user'];
ds.automigrate(lbTables, function(er) {
  if (er) throw er;
  console.log('Looback tables [' + lbTables + '] created in ', ds.adapter.name);
  ds.disconnect();
});
````
And here's a portion of resource.json (model).

````
  "relations": {
    "types": {
      "type": "hasAndBelongsToMany",
      "model": "type",
      "foreignKey": ""
    },
    "audiences": {
      "type": "hasAndBelongsToMany",
      "model": "audience",
      "foreignKey": ""
    },
    "locations": {
      "type": "hasAndBelongsToMany",
      "model": "location",
      "foreignKey": ""
    },
    "comments": {
      "type": "hasMany",
      "model": "comment",
      "foreignKey": ""
    }
  },
````

But when I run the app, I get this error.

````
ERROR:  relation "public.resourcelocation" does not exist at character 44
STATEMENT:  SELECT "id","resourceid","locationid" FROM "public"."resourcelocation" WHERE "resourceid" IN ($1) ORDER BY "id"
```

**Comment by WorldWideWebb** [comment]
I have the same issue as faustomorales.  Did you ever find a solution to this? Can't find documentation for this anywhere.

**Comment by peterholcomb** [comment]
@faustomorales @WorldWideWebb I believe the issue is that you need to add the join table in your automigrate script.  For example, I had a situation where i have a user hasAndBelongsToMany relation to Group.  In my automigrate script, I added the 'userGroup' as a table that needs to be created:

`var server = require('./server');
var ds = server.dataSources.postgres;
var lbTables = ['user', 'AccessToken', 'ACL', 'RoleMapping', 'Role', 'Organization', 'Group', 'View', 'userGroup'];
ds.automigrate(lbTables, function(er) {
  if (er) throw er;
  console.log('Loopback tables [' + lbTables + '] created in ', ds.adapter.name);
  ds.disconnect();
});
`
