### ISSUE TITLE
Large Object Client Support (lo_export, lo_import, etc)

### ISSUE THREAD

**Issue by entropathy** [strongloop/loopback-connector-postgresql#103]
I've been attempting to access a large object in a PG database. I'm porting an application from PHP , and in this app the PHP function pg_lo_export is used to achieve extract this data column from the db. 

Is there any such analog in this connector or I guess in the Postgersql libraries. I've tried using pg-native to back this connector but this doesn't seem to have made any difference.

Any help regarding the lo_\* family of functions would be greatly appreciated.

**Comment by superkhau** [comment]
@raymondfeng I'm not about this one. PTAL.

**Comment by entropathy** [comment]
FWIW I was able to get this working , it required additions to libpq , and subsequently all the way up the chain , I'm not sure it's 100% correct and am still testing , but I was able to get the data exported on the client. I will generate patches for the various projects and open issues there.

**Comment by superkhau** [comment]
Would you like to submit a pull request with your patch?

**Comment by entropathy** [comment]
I'd be happy to but do have some questions. The functionality comes straight out of the pq library/module, which means it's dependent on pg-native, is there a proper way to degrade the function in the absence of pg-native , or should it just report an error , or should it not matter and the degradation should happen in the pg module , I'm somewhat new to a lot of this and am unsure of best practices.

Second question, would you want me to submit a patch now, or should I wait until I get patches accepted in the pq and pg/pg-native modules ?
