### ISSUE TITLE
Indexes definition doesn't work with postgresql connector

### ISSUE THREAD

**Issue by Neil-UWA** [strongloop/loopback-connector-postgresql#104]
There are two ways to define indexes in loopback. 
1:  in property level
```
 {
   "properties": {
       "name: {"type": "stirng", "index": { "unique": true}}
   }
}
```

2: define an index in indexes 
```
"indexes": {
  "name_index": {
    "keys": {
      "name": 1
   }, 
   "options": {"unique": true}
  }
}
```

However, neither works with postgresql connector. I've created a test repository https://github.com/Neil-UWA/loopback-pg-index-issue.

**Comment by Klowner** [comment]
My branch supports index creation, you're welcome to give it a try.
https://github.com/Klowner/loopback-connector-postgresql

There's also PR that's been sitting for 6 months #64

**Comment by Neil-UWA** [comment]
@Klowner thanks for the input, I will definitely give it a try:)

**Comment by geekguy** [comment]
Any update on this issue ?

**Comment by superkhau** [comment]
Sorry for the late reply. Would one of you guys like to submit a PR?

**Comment by geekguy** [comment]
@superkhau : Looks like fix is in master (https://github.com/strongloop/loopback-connector-postgresql/pull/64)

Can we do a version bump ?

**Comment by superkhau** [comment]
Are you having issues installing v2.4.0? It looks like @raymondfeng released it 3 days ago.

**Comment by geekguy** [comment]
Err. Din't check the latest release. Works fine. We can close this issue.

**Comment by Neil-UWA** [comment]
Don't have time to test it right now, but it can be closed since the feature has been released.
