### ISSUE TITLE
Unique constraint on 3 properties

### ISSUE THREAD

**Issue by jdrouet** [strongloop/loopback-connector-postgresql#111]
Hi,
I am actually looking for creating dynamically a unique constraint on 3 properties. Here is my json which is not working :

``` json
    "relations": {
      "a": {
        "type": "belongsTo",     
        "model": "ModelA",
        "foreignKey": "modelAId"
      },
      "b": {
        "type": "belongsTo",
        "model": "ModelB",
        "foreignKey": "modelBId"
      },
      "c": {
        "type": "belongsTo",
        "model": "ModelC",
        "foreignKey": "modelCId"
      }
    },
    "indexes": {
      "my_unique_constraint": { 
        "keys": {
          "modelAId": 1,
          "modelBId": 1,
          "modelCId": 1
        },
        "options": {
          "unique": true
        }
      }
    },
```

But actually it doesn't create any unique constraint on these fields. Do you know how to do that ?

**Comment by superkhau** [comment]
@crandmck Do we have docs for this use case?

**Comment by crandmck** [comment]
All we have is https://docs.strongloop.com/display/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Indexes and it looks like his JSON is correct based on that.

**Comment by superkhau** [comment]
@jdrouet Can you provide a link to a test project on GitHub? See https://github.com/strongl    oop/loopback/wiki/Reporting-issues#bug-report

**Comment by Neil-UWA** [comment]
the index support feature is not complete actually, loopback will not create any indexes based on the declaration for now. Klowner's pull request on index-feature has been merged, but the repo doesn't release it https://github.com/strongloop/loopback-connector-postgresql/pull/64

**Comment by raymondfeng** [comment]
I'll release it soon

**Comment by raymondfeng** [comment]
Released as 2.4.0.

**Comment by timneedham** [comment]
This still seems to be an issue in 2.4.1?

**Comment by crandmck** [comment]
It's not clear to me that is just a doc issue.  @raymondfeng @superkhau 

It's also not clear to me what exactly needs to be updated or changed in the docs--suggestions appreciated.

**Comment by kodepareek** [comment]
Hi guys

I am on LB 3. 

I have `team` and `appUser` models which are linked by `hasManyThrough` via a `teamappUser` model. 

I created a unique together constraint on `teamId` and `appUserId` on in the `teamappUser` 

On testing for duplicate key creation (testing if unique together constraint was successful ) I get a 500 internal server error and server restart. 

I feel a 500 is completely unwarranted for what is expected behaviour on part of the app. This should be a 4XX error and should not cause the server to crash.
