### ISSUE TITLE
How to disable lowercase for models, tables and fields?

### ISSUE THREAD

**Issue by Sogl** [strongloop/loopback-connector-postgresql#116]
Hi!

I use loopback with my postgres DB and found a problem. All my models, tables and fields become lowercase. 

What I create in `arc`:
![image](https://cloud.githubusercontent.com/assets/7556290/10862931/df143ed0-7fff-11e5-838e-9b9041e73ddc.png)

And finally what I see in DB after pressing `Migrate Model` button:
![image](https://cloud.githubusercontent.com/assets/7556290/10862933/f44620ac-7fff-11e5-8f8f-2954cb8c3167.png)

I use CamelCase and for me it's very bad moment.

**Comment by superkhau** [comment]
@crandmck Do we have docs explaining how to convert case or whether it's possible or not?

**Comment by crandmck** [comment]
No, we don't have docs for specifying table name case preferences for auto-migration, and:

1. I'm not even sure if it's consistent across all dbs that support auto-migration.  
1. I don't know how one would change this behavior.  I suspect it's not supported (without modifying the connector implementation), but I don't know for sure.
2. Would this be database-specific?  I would presume so, since each connector implements auto-migration itself.

@raymondfeng would know.

**Comment by Sogl** [comment]
@crandmck,
I also found this issue:
https://github.com/strongloop/loopback-connector-postgresql/issues/38

And fork with changes to fix some parts of the problem:
https://github.com/W3GroupFinland/loopback-connector-postgresql

Any chance to merge?

**Comment by Sogl** [comment]
Also I found bug with `discovery models`. If I discover model and try to migrate it after change in `Strongloop Arc` - I see error `column %name% already exists`. 
But the same situation with manually creating model in `arc` works fine. I can create model from scratch and migrate it many times (with and without changes).

My module versions:
```
loopback@2.22.2
loopback-boot@2.14.0
loopback-datasource-juggler@2.41.1
loopback-connector-postgresql@2.3.0
loopback-component-explorer@2.1.1
```

**Comment by crandmck** [comment]
@Sogl It looks like #38 covers this bug.  You can ask @raymondfeng about merging it.

Re: the above bug, please open a separate issue.  I'll close this one.

**Comment by PhanindraKumar** [comment]
@crandmck  Hi is this issue is resolved?, because i got the same issue in the version 2.8.0.

**Comment by crandmck** [comment]
I don't know.  Maybe @raymondfeng knows?

**Comment by howientc** [comment]
I've found a simple solution to keeping mixed case that doesn't require modifying the connector source. I am running version 3.1.0 of  loopback-connector-postgresql

Example: In a boot script (server/boot/z_my_script.js):

```
// First get my DataStore that runs on postgres:
const server = require('../server');
const ds = server.dataSources.myDataSource;

// override PostgreSQL.prototype.dbName in postgresql.js: 
ds.connector.dbName = name => name // just use the name as-is!
```

I also have a call to DataSource.discoverAndBuildModels which I used to generate a model for a database view. That, too, has issues with case that can be solved by explicitly passing **nameMapper:null** as below:

`ds.discoverAndBuildModels(v.name, {visited: {}, associations: true, nameMapper: null})`
