### ISSUE TITLE
Can't migrate model after discover

### ISSUE THREAD

**Issue by Sogl** [strongloop/loopback-connector-postgresql#117]
Hi!
I use `Stronloop Arc` and `loopback postgresql connector`.

If I discover model and try to migrate it after change (or without any change) in `Strongloop Arc` - I see error `column %name% already exists`. 
But the same situation with manually creating model in `arc` works fine. I can create model from scratch and migrate it many times (with and without changes).

My module versions:
```
loopback@2.22.2
loopback-boot@2.14.0
loopback-datasource-juggler@2.41.1
loopback-connector-postgresql@2.3.0
loopback-component-explorer@2.1.1
```

**Comment by superkhau** [comment]
Please post Arc related issues at https://github.com/strongloop/strong-arc/issues.

**Comment by superkhau** [comment]
If you feel this is a LoopBack related issue, please comment again and I will reopen the issue.
