### ISSUE TITLE
isActual method EventEmitter memory leak detected

### ISSUE THREAD

**Issue by LancelotP** [strongloop/loopback-connector-postgresql#118]
Hi everyone,

As I was looking around this connector I wanted to try the `isActual` method in order to run the `autoupdate` method only when needed.

The thing is... I ran into this :

```
The database is reponding: true
(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DataSource.addListener (events.js:239:17)
    at DataSource.once (events.js:265:8)
    at PostgreSQL.SQLConnector.execute (/src/node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:396:28)
    at PostgreSQL.getTableStatus (/src/node_modules/loopback-connector-postgresql/lib/migration.js:44:10)
    at /src/node_modules/loopback-connector-postgresql/lib/migration.js:124:12
    at /src/node_modules/loopback-connector-postgresql/node_modules/async/lib/async.js:122:13
    at _each (/src/node_modules/loopback-connector-postgresql/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/src/node_modules/loopback-connector-postgresql/node_modules/async/lib/async.js:121:9)
    at PostgreSQL.isActual (/src/node_modules/loopback-connector-postgresql/lib/migration.js:123:11)
    at DataSource.isActual (/src/node_modules/loopback-datasource-juggler/lib/datasource.js:1676:20)
Test isActual method return: undefined
```

The method is called from within /server/boot/script.js:

``` js
module.exports = function (loopback) {

  var ds = loopback.dataSources.storage;

  ds.ping(function callback(err, data) {
    console.log('The database is reponding:', (data[0].result === 1 ? true : false));
  })

  console.log('Test isActual method return:', ds.isActual());
}
```

The `ds.ping()` function allow me to be sure that the database is correctly connected with loopback since there are in two separate dockers

Finally storage is defined in datasources.json :

``` json
{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "storage": {
    "host": "postgres",
    "port": "5432",
    "database": *DATABASE*,
    "username": *USERNAME*,
    "password": *PASSWORD* ,
    "name": "storage",
    "connector": "postgresql"
  }
}
```

Maybe have I done something wrong with but I would like to know if I am the only one with this issue.

Versions:

```
npm: 2.14.4
node: 4.1.2
strongloop: 5.0.1
loopback: 2.22.2
loopback-connector-postgresql: 2.4.0

docker: 1.8.3
docker-machine: 0.4.1
docker-compose: 1.4.2
mac os x: 10.11.1
```

**Comment by Cornik34** [comment]
After digging a little I found that I was misusing `isActual`.

It's working ok with this:
``` js
ds.isActual(['Customer'], function callback(err, data) {
  console.log('isActual: ', err, data)
});
```

But if I do not specify a `string` or an `array` and if I have more than 10 tables to compare against the models defined in the app, Node warns me with the message above.

Another thing, if only one table is not up to date, the function returns false and I do not have any information on which table is not up to date. Is there a function that can return anything more precise than juste false if any of the tested tables is not up to date ?

I have a workaround where I test one by one every model within the datasource to avoid the limit of emitter listeners and to know exactly what table is not up to date, but I would like to know if there is anything already in place to do that ?

**Comment by ssh24** [comment]
@LancelotP There is no function in place currently to figure out if **a** loopback model is out of date with the corresponding database table structure. As you stated, you need to iterate through the list of models and check them using `ds.isActual(model, cb)`.

To solve the listener issue you can set the max listener to `Infinity or 0`. Read more [here](https://nodejs.org/docs/latest/api/events.html#events_emitter_setmaxlisteners_n)
```js
process.setMaxListeners(0);
```

Closing this as resolved. Feel free to reopen if needed.
