### ISSUE TITLE
When new required fields with a default value are added autoupdate shouldn't fail

### ISSUE THREAD

**Issue by alFReD-NSH** [strongloop/loopback-connector-postgresql#123]
Steps to produce:

1 - Create a model and run autoupdate/automigrate
2 - Add a new required property with a default value to the model for example:

```
    "newProperty": {
      "type": "Number",
      "required": true,
      "default": 0
    }
```

3 - Run autoupdate again

What's expected: New column should be added with the default value.

What actually happens: Autoupdate fails here and throws this:

```
error: column "newProperty" contains null values
```

It happens because it tries to add column with `NOT NULL` constraint, but this is only possible, if we give a default value, but `loopback-connector-postgresql` ignores the given default value in the model configuration.

I would like to contribute this myself, but I'm not sure if I'm getting the test configuration to work. I'm getting `error: password authentication failed for user "user"` for the first test, but the credentials in the configuration are correct and also a lot of other tests are failing.

**Comment by Elindorath** [comment]
@raymondfeng @superkhau @bajtos : I would like to address this issue, but I'm unable to run the test right now. I saw on the Readme that I need to contact you for instructions so I do.

**Comment by raymondfeng** [comment]
@Elindorath You have two ways to configure your postgres connection.

1. Set up env vars (https://github.com/strongloop/loopback-connector-postgresql/blob/master/test/init.js#L10)
```
export CI=true
export TEST_POSTGRESQL_HOST=localhost
export TEST_POSTGRESQL_PORT=5432
export TEST_POSTGRESQL_USER=myUser
export TEST_POSTGRESQL_PASSWORD=myPassword
```

Or drop `.loopbackrc` file into your home dir:
```
{
    "test": {
        "postgresql": {
            "host": "localhost",
            "port": 5432,
            "database": "test",
            "username": "test",
            "password": "testpass"
        }
    }
}
```

Please also use https://github.com/strongloop/loopback-connector-postgresql/blob/master/test/tables.sql to populate your test db.

**Comment by Elindorath** [comment]
Thanks @raymondfeng. I'll try to give you an update this week-end.

**Comment by zihehuang** [comment]
Any update on this issue? I am running into the same issue.

**Comment by kutsyk** [comment]
Is this fixed?

**Comment by bvanleeuwen1995** [comment]
To me this seems to be still a bug, either defaultFn or default is not honerred during migrations and it will fail.

**Comment by ptmccarthy** [comment]
I'm still running into this issue today

**Comment by bartshappee** [comment]
I ran into this today as well, the manual workaround is dangerous in the long term

**Comment by devpascoe** [comment]
same

**Comment by bitmage** [comment]
I'm running into this today, and it's breaking our production deploy.

**Comment by bitmage** [comment]
Ended up running manual ALTER statements.  :-1:

**Comment by kgrvamsi** [comment]
@raymondfeng @bajtos  need your help here how to resolve this issue?is this fix part of the connector or we need to do this patch on the existing library to bypass the main issue?

**Comment by piuspbd** [comment]
Still running into the issue today.

**Comment by sraddhan** [comment]
For those who end up here and are wondering about the status of the issue, there's similar issue reported which is open as of this moment. [here is the link](https://github.com/strongloop/loopback-next/issues/3058).

**Comment by ketansp** [comment]
Need to open this again. This is still an issue in 2024.
