### ISSUE TITLE
Ability to specify property as foreign key

### ISSUE THREAD

**Issue by antonsamper** [strongloop/loopback-connector-postgresql#124]
Putting aside Loopback relations as they don't modify the database, there is currently no way to specify in the model schema that a particular property is a foreign key.

It would be great to have this in order to maintain data integrity.

For example:

``` javascript
"properties": {
      "userID": {
        "type": "Number",
        "required": true,
        "postgresql": {
          "columnName": "user_id",
          "dataType": "integer",
          "constraints": {
            "type": "Foreign Key",
            "name": "fk_order_user_id",
            "referencedTable": "user",
            "referencedColumn": "id",
            "onDelete": "No Action",
            "onUpdate": "No Action",
            "validation": "Not Deferrable",
          }
        }
      }
```

**Comment by balmasich** [comment]
+1

**Comment by Xflofoxx** [comment]
+2

**Comment by ramanaveli2i** [comment]
+3

**Comment by alexda14** [comment]
+666

**Comment by superkhau** [comment]
@raymondfeng Any input on this feature?

**Comment by raymondfeng** [comment]
I'm fine to support such extensions. Two questions:

1. Do you add `constraints` for the purpose of `automigrate/autoupdate`?
2. Do you expect `discovery` to populate such information?

**Comment by petermetz** [comment]
Hi @raymondfeng 


Huge up for this one!

Can't speak for the OP, but I would say to both questions the answer is yes:

Would be nice to control the foreign keys from my loopback models and in other scenarios I want to be able to reverse engineer an existing schema into model json files with the help of ```discovery```.


Kind regards,
Peter

**Comment by raymatos** [comment]
Agree, if models are going to generate the schema then it would make sense to also include FK

**Comment by tatianacmh** [comment]
+1

**Comment by jpinkster** [comment]
+1

**Comment by f0rmiga** [comment]
Any updates on this feature?

**Comment by ssh24** [comment]
Bumping this up. Should use the same property as MySQL does to state foreign keys. Look [here](https://github.com/strongloop/loopback-connector-mysql#auto-migrateauto-update-models-with-foreign-keys).

**Comment by gfrancqu** [comment]
any updates on this feature ?

**Comment by rpalacio86** [comment]
+1

**Comment by osazemeu** [comment]
Anyone working on this?

**Comment by pablozandona** [comment]
+1

**Comment by YuriScarbaci** [comment]
+1
