### ISSUE TITLE
How to specify a different schema than public on datasource for model discovery

### ISSUE THREAD

**Issue by dopeddude** [strongloop/loopback-connector-postgresql#125]
I am trying for discovering the models from my postgres database, using `$ slc arc` graphical way.

The tables on my database reside on a different schema than `public`.

I am not able to figure out how to specify a different schema name to fetch the tables on that schema and then generate my models.json.

**Comment by mrkswrnr** [comment]
Best workaround I found for defining a different schema than public was to alter the datasource user/role:
`ALTER ROLE your_datasource_username SET search_path = your_schema`

If you delete `options.postgresql.schema` from the model.json afterwards the datasource will always use the schema defined in the role's search_path.

**Comment by dopeddude** [comment]
Have tried with that also, That does work well when I run a web server out of my project say using `$ node server/server.js`

But, the search_path is not honoured when I use command `$ slc arc` for model discovery from pg database.

**Comment by ssh24** [comment]
Similar to [this](https://github.com/strongloop/loopback-connector-postgresql/issues/32). You can specify the schema name on the `discoverSchema` function like this:

```js
ds.discoverSchema(tableName, {schema: <my_schema>}, cb);
```

Closing this as duplicate. Feel free to reopen if needed.
