### ISSUE TITLE
Geopoint comparison fails due to non-existent operator

### ISSUE THREAD

**Issue by daamsie** [strongloop/loopback-connector-postgresql#126]
The pgsql connector is using the = operator to compare geopoints when it should be using ~=

I have code like to this

```
var location = new loopback.GeoPoint({lat: ctx.args.data.location.lat, lng: ctx.args.data.location.lng});

Stop.app.models.Place.find(
      { where: { and: [
            {userid: ctx.args.data.userid},
            {location: location}
          ]
        }
      }, ...
```

With debug on, the console returns a query like this. 

```
SELECT "place_id","userid","country_id" FROM "public"."places" 
WHERE ("userid"=$1) AND ("location"= point($2,$3)) ORDER BY "place_id" LIMIT 1

```

Postgresql returns the following error: 
`operator does not exist: point = point`

The solution to this seems to be to adjust the operator to not use = , but use ~= instead.

**Comment by 0candy** [comment]
@daamsie Could you please provide a sample sandbox to reproduce your issue? Thanks!
See http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report

**Comment by daamsie** [comment]
I'm not really using loopback much right now and am short on time so I'm overloaded with other things to do so I'm unlikely to get you this sandbox I'm afraid. However, I think my description above describes the issue clearly enough and even includes the solution to the issue. Hopefully you can act on it.

**Comment by timlind** [comment]
I'm seeing a similar issue except that the generated SQL simply doesn't have an operator at all. This is true for using `{ near: {lat,lng}}` as well.

SQL generated: ... `AND ("geolocation"point($4,$5)) ` ...
SQL error: `error: syntax error at or near "point"`
Query via REST: `{"geolocation":{"lat":36.778261,"lng":-119.41793239999998}}`
Alternative query via REST: `{"geolocation":{"near":{"lat":36.778261,"lng":-119.41793239999998}}}`

loopback@2.36.0
loopback-connector-postgresql@2.7.0
loopback-datasource-juggler@2.53.0

**Comment by gregdingle** [comment]
#191  might be related.

**Comment by ofekd** [comment]
I'm also getting the error @timlind described -- can someone point me to the responsible files? I'll try and fix the issue

**Comment by gregdingle** [comment]
@ofekd See https://github.com/strongloop/loopback-connector-postgresql/blob/ce2d382a0dfecdde234eaaeb01b8c75700f38bc4/lib/postgresql.js#L386 and https://github.com/strongloop/loopback-connector/blob/master/lib/sql.js#L730 . Good luck! 😄

**Comment by ofekd** [comment]
Update: After bumping into anpther issue (no deep querying) with the same specific model/connector comibnation, we ended up writing our on methods using `knex`. Was too much work to fix both issues.

If the project will have enough badnwidth left I'll turn our knex code into a connector. If anyone's interested, let me know

**Comment by gregdingle** [comment]
@ofekd I'm interested. How did you integrate knex with loopback? Do you execute knex-emitted sql with a loopback connection, or do you execute a knex query and construct loopback objects with the raw results of the query?

**Comment by ssh24** [comment]
This issue has been fixed and should be available on the next release of the connector.
