### ISSUE TITLE
Rename a foreignKey - columnName? 

### ISSUE THREAD

**Issue by peek4y** [strongloop/loopback-connector-postgresql#130]
Expecting something like this... Is this possible?

```
"relations": {
  "orders": {
      "type": "hasMany",
      "model": "Orders",
      "foreignKey": "userId",
      "postgresql": {
        "columnName": "user_id"
      }
    }
}
```

**Comment by lius** [comment]
you could solve this in belongsTo mapping in orders, setting the foreign key to the name of the model property, as usually done, and in the definition of property, specify the option with the name of the column.

**Comment by peek4y** [comment]
Hmm, but isn't there any other way, like in the example I've mentioned?

**Comment by mplaza** [comment]
you can add the foreign key as a property and change the column name from there, like:

"properties": {
"userId": {
      "type": "number",
      "postgresql":{
        "columnName": "user_id"
      }
    },
},
"relations": {
  "orders": {
      "type": "hasMany",
      "model": "Orders",
      "foreignKey": "userId",
}
}
