### ISSUE TITLE
loopback will not force a `postgresql` dataType for embedded relation

### ISSUE THREAD

**Issue by sidewaiise** [strongloop/loopback-connector-postgresql#131]
When using `embedOne` relation type, we cannot specify to use a postgresql `dataType`: "TEXT" and have autoUpdate update the column. The column defaults to varchar(1024).

Here is the sample JSON:

```
    "agentSignature": {
      "type": "embedsOne",
      "model": "Signature",
      "property": "agentSignature",
      "options" : {
        "validate": true,
        "forceId": false
      },
      "postgresql": {
        "dataType": "TEXT",
        "nullable": "YES"
      }
    }
```

and here is an example of the generated database column:

![screen shot 2016-03-16 at 1 18 11 pm](https://cloud.githubusercontent.com/assets/5085804/13800588/837f5456-eb7a-11e5-8a7e-7e688ebe54bb.png)

Essentially, we need the column to store long TEXT strings in JSON format, the JSON being a row of the Signature model.

This seems to be a problem with the way loopback-connector-postgresql handles embedded relations - it doesn't seem to take tabled data structures into account when using nested return values. This may also be a problem with loopback-datasource-juggler.

Any insight into the issue or fixes to the repo would be much appreciated.

Cheers.

**Comment by madianas** [comment]
What about embedsMany? I am having the same issue. It's not picking up "TEXT" datatype

>     "tierprograms": {
      "type": "embedsMany",
      "model": "Tier",
      "property": "tiers",
      "options": {
        "validate": true,
        "forceId": true,
        "persistent": true
      },
      "postgresql": {
        "dataType": "text",
        "nullable": "YES"
      }

**Comment by lius** [comment]
I'm using embedsMany and embedsOne without problems, with json and jsonb data types on database (I did not use the schema generation feature). Also, I'm not specifying a data type specific for postgres per column, just using LB types array and object for model properties. In that case, the values are serialised into strings, working perfectly with json/jsonb types, that works receiving strings as an input.

**Comment by 0candy** [comment]
Closing this issue as fix has been merged.
