### ISSUE TITLE
Filter on relation doesn't respect id constraint

### ISSUE THREAD

**Issue by mneil** [strongloop/loopback-connector-postgresql#134]
**The setup**

User hasMany through accounts
Accounts hasMany through users

**The problem**
Retrieving users from accounts by id fails to correctly constrain the result set.

I expect `/api/accounts/1/users?filter={"where":{"id":2}}` to return 1 result - the user by id belonging to account id 1.

**What happens**
I receive 2 users, both myself and the user of id 2

What is happening is that the ctx.query.where is coerced from `{"where":{"id":2}}` to `{"where":{"id":{"inq":[1,2]}}}` where 1 is the owner of the access token being used. If I authenticate as user id 5 then the query is coerced to `{"where":{"id":{"inq":[5,2]}}}`

**How to reproduce**
I am using Ubuntu 14.04 trusty
Install Postgres 9.3.11
Create an empty database and edit `server/datasources.json` to authenticate and use that database.

Do the following:
```
git clone git@github.com:mneil/loopback-sandbox.git
npm install
slc run
```

On boot you should see 2 messages after strongloop connects 
```
auto migrate  undefined
database filled
```

This creates 2 users, roles, and an account. Open your browser to http://localhost:3000/explorer

Authenticate the explorer with 
```
{"username":"admin","password":"admin"}
```

Now GET `/api/accounts/1?filter={"include":"users"}` and see that 2 users return. < correct

**The following are incorrect**
GET `/api/accounts/1?filter={"include":"users","where":{"id":2}}` returns 2 users
GET `/api/accounts/1/users?filter={"where":{"id":2}}` returns 2 users

**Comment by mneil** [comment]
I tried this with the mysql connector and it does the same thing. I have opened a ticket for the same issue in the loopback module https://github.com/strongloop/loopback/issues/2211 if you want to close this one. I'm leaving it open in both places just in case someone can confirm the issue is in one repo or the other.

Thanks!

**Comment by 0candy** [comment]
Closing this in favor of the other one you created. strongloop/loopback#2211
