### ISSUE TITLE
discoverAndBuildModels with Postgres does not work

### ISSUE THREAD

**Issue by remkohdev** [strongloop/loopback-connector-postgresql#135]
I can write a script and pull schemas from the database and write it to a file too. The discoverAndBuildModels method seems to promise though that it generates the model after discovery.

loopback and loopback-connector-postgresql: 2.11.3

Documentation:
discoverAndBuildModels
Discover and build models from the specified owner/modelName.

For me on Postgres this works fine

`ds_pg.discoverModelDefinitions(options1, function (err, models) {
console.log(models);
models.forEach(function (def) {
console.log(def.name);`

but with the same configuration for discoverAndBuildModels, no models are returned at all. 

Related but slightly different behavior on DashDB (DB2) on Bluemix
https://github.com/strongloop/loopback-connector-db2/issues/28

or this on StackOverflow:
http://stackoverflow.com/questions/26128285/loopback-discoverandbuildmodels-not-generating-models

Is this just something that needs to be pulled instead of shipped?

**Comment by ssh24** [comment]
@remkohdev Do you have a sample script to show your work? Here is an example of mine, I have a table called `books` in my postgres database and when I try call `discoverAndBuildModels` on it, it is done this way:

```javascript
// Discover and build models from books table
ds.discoverAndBuildModels('books', {schema: 'public', relations: true}, function(err, models) {
  if (err) console.log('Err: ' + err);
  if (models) {
    Object.keys(models).forEach(function(key) {
      console.log('working on', key);
    });
  }
});
```

**Comment by ssh24** [comment]
@remkohdev Since this issue has not been active, closing this. Hopefully my script would solve your problem. Feel free to reopen the issue if there are any further questions.
