### ISSUE TITLE
[TYPO] Nullability is missing a space

### ISSUE THREAD

**Issue by hyatt03** [strongloop/loopback-connector-postgresql#136]
The sql statement generated on the following line: https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/migration.js#L262

is missing a space after ALTER COLUMN

**Comment by superkhau** [comment]
Would you like to submit a PR and a test case to reproduce your issue?

**Comment by hyatt03** [comment]
@superkhau Yes
