### ISSUE TITLE
Upgrade pg to the latest.

### ISSUE THREAD

**Issue by alFReD-NSH** [strongloop/loopback-connector-postgresql#139]
Current version doesn't support node v6.

**Comment by th0mas** [comment]
Indeed, I cannot connect to PostgreSQL from my LoopBack app anymore with Node v6. 
In pg v4.2.0 the connect function fails, but works with v4.5.5.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-connector-postgresql/pull/143
