### ISSUE TITLE
whats the property way tu run a sql postgres command ??

### ISSUE THREAD

**Issue by Rikhart** [strongloop/loopback-connector-postgresql#14]
There are a way that a allow me run a sql code like the sequelize orm module ?? (http://sequelizejs.com/docs/1.7.8/usage#raw-queries )

sequelize
  .query('SELECT * FROM projects', Projects)
  .success(function(projects){
    // Each record will now be mapped to the project's DAO-Factory.
    console.log(projects)
  })
 Thanks for answers.

**Comment by davidcheung** [comment]
Cleaning up old issues, looks like this question was answered.
Closing issue now.
