### ISSUE TITLE
id column does not use columnName

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-connector-postgresql#148]
if you have an id property with a name different to the column name, the columnName is not used, leading to sql errors.

			"name": "id",
			"postgresql": {
				"owner": "public",
				"tableName": "address_type",
				"columnName": "_id",
				"column": "_id",
				"dataType": "uuid",
				"dataLength": null,
				"dataPrecision": null,
				"dataScale": null,
				"nullable": "NO",
				"type": "String"
			},
			"type": "string"

gives the error
```
    {
      "error": {
      "name": "error",
      "status": 500,
    "message": "column \"id\" does not exist",
    "length": 95,
    "severity": "ERROR",
    "code": "42703",
    "position": "70",
    "file": "parse_relation.c",
    "line": "2892",
    "routine": "errorMissingColumn"
   }
  }
```

**Comment by jmls** [comment]
ok, so I tracked this down to idinjection. if not defined on the model, the behaviour above happens. if defined as false, then the system works.

So, at a guess, the idInjection flag defaults to true, and creates _another_ id field which doesn't have a corresponding postgresql columnName

**Comment by superkhau** [comment]
Can you provide a sample repo for us to produce the issue on our end? https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by deepakrkris** [comment]
@jmls yes, IdInjection must be set to false, to customize id fields.
