### ISSUE TITLE
Getting time zone not recognized error

### ISSUE THREAD

**Issue by woodedlawn** [strongloop/loopback-connector-postgresql#15]
I'm following the instructions for defining an admin role in the documentation, but I'm receiving the following error at the ```Role.create({name: 'admin'}, cb)``` step:
```
loopback:connector:postgresql error: time zone "gmt-0700" not recognized
```
Any help would be appreciated!

**Comment by davidcheung** [comment]
Cleaning up old issues, https://github.com/strongloop/loopback-datasource-juggler/commit/3edee5c4c59a4ccc3e72d39d84c929ad29185eda address this issue, closing issue now.

**Comment by snevolin** [comment]
I have the same issue with loopback 3.0.0

**Comment by edbond** [comment]
For me the problem was in setting updatedAt to number. Changed to Date object.

```js
  Model.observe('before save', function (ctx, next) {
    var instance = ctx.instance || ctx.data;

    // instance.updatedAt = Date.now();
    instance.updatedAt = new Date();

    next();
  });
```
