### ISSUE TITLE
error when performing autoupdate

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-connector-postgresql#154]
I am trying to sync a postgresdb with my models, using this code:

```
ds = loopback.datasources['myDS'];

ds.autoupdate((err) => {
});
```

however, when I do, I get the error

```
"error": {
    "name": "error",
    "status": 500,
    "message": "column \"[object object]\" does not exist",
    "length": 97,
    "severity": "ERROR",
    "code": "42703",
    "file": "indexcmds.c",
    "line": "994",
    "routine": "ComputeIndexAttrs",
    "stack": "error: column \"[object object]\" does not exist\n    at Connection.parseE (/workspace/myapp/node_modules/pg/lib/connection.js:539:11)\n    at Connection.parseMessage (/workspace/myapp/node_modules/pg/lib/connection.js:366:17)\n    at Socket.<anonymous> (/workspace/myapp/node_modules/pg/lib/connection.js:105:22)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:146:16)\n    at Socket.Readable.push (_stream_readable.js:110:10)\n    at TCP.onread (net.js:523:20)\n    at TCP.onread (/workspace/myapp/node_modules/async-listener/glue.js:188:31)"
  }
```

the models have both indexes and relations. These appear to be working properly as they appear in the explorer (but I obviously can't query as the models are not synced to the db)

what am I doing wrong ?

**Comment by raymondfeng** [comment]
Try to dump out the SQL statements using `DEBUG=loopback:connector:*` env var.

**Comment by jmls** [comment]
ach; turns out that the "column [object object]" was my problem: the json was malformed;

however, there's another issue:

I thought that autoupdate would "merge" changes into the db

I am now getting the error

```
{
  "error": {
    "name": "error",
    "status": 500,
    "message": "relation \"salesRep\" already exists",
    "length": 83,
    "severity": "ERROR",
    "code": "42P07",
    "file": "index.c",
    "line": "779",
    "routine": "index_create"
}
```
shouldn't it drop / overwrite the index ?

**Comment by jmls** [comment]
ok, I think I know what is happening : I have two models, Salesrep with an index name of "salesRep" and Customer, which has a fk index called "salesRep"

I have not added *index: 1* to the property definition, but simply defined the index with keys: {}

However, it seems that in *loopback-connector-postgresql/lib/migration.js* around line 722 (_// add single-column indexes_) it assumes that a "single-column" index *must* have the index key set.

Otherwise the index is defined using the _multi-column indexes_ loop

so we now have 2 problems: 

1) the single-column index is actually defined using the multi-column index loop. Therefore the practice of
 ```
 // The index name used should match the default naming scheme
      // by postgres: <column>_<table>_idx
```
is not followed

and 

2) any index defined by the multi-column index loop *must* have a unique name. Perhaps it would be better to have a convention of "\<index name\>_\<tablename\>"

**Comment by deepakrkris** [comment]
@jmls foreign key references configured as relations does not create "indexes" in this connector

**Comment by deepakrkris** [comment]
@jmls 
Can you provide a sample for us to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report
