### ISSUE TITLE
duplicate foreign key if defined as property

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-connector-postgresql#162]
In a model  _Order_ I have a property called _customerId_. I also have a relation that defines a "belongsTo" and specifies the _customer_ table, with a foreignKey of _customerId_

This all works well with an existing database. however, in a new database, using either autoupdate or automigrate, the sync fails because it's trying to create a duplicate _customerId_ field

Is there an option to tell the migration not to try and create duplicate fields and indexes if they already exist in the schema / model ? Or can I add an option to the property to tell strongloop that this *is* a foreignkey ?

**Comment by deepakrkris** [comment]
@jmls relations should not have an impact on autoupdate or automigrate, since there is no support to add/modify foreign keys. I have tested this and I am not able to recreate this issue. 
perhaps it could be related to some other issues in the code.

**Comment by deepakrkris** [comment]
@jmls 
Can you provide a sample for us to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by deepakrkris** [comment]
@jmls , Ok I understand the issue now. This is related to foreign key columns and not foreign hey constraints in tables. 
The current convention is that foreign key columns are supposed to be configured only as relations. There is no reason to introduce a new feature to configure them under model properties.
Please let us know if you have any specific reason behind this.
