### ISSUE TITLE
update the “pg” dependency ?

### ISSUE THREAD

**Issue by upupzealot** [strongloop/loopback-connector-postgresql#164]
See the topic here.
https://github.com/strongloop/loopback-connector-postgresql/issues/138

**Comment by davidcheung** [comment]
@upupzealot the latest version is `6.1.0` and `^6.0.0` will pick that up, 
can you clarify please?
https://github.com/strongloop/loopback-connector-postgresql/blob/master/package.json#L23

**Comment by 0candy** [comment]
`pg` dependency has already been upgraded. https://github.com/strongloop/loopback-connector-postgresql/pull/143
Closing this issue.
