### ISSUE TITLE
discoverPrimaryKeys doesn't return primary keys

### ISSUE THREAD

**Issue by mastergap** [strongloop/loopback-connector-postgresql#17]
Hi, I'm trying to use the discover APIs to connect to an already existing Postgres database and build the models automatically. I found that the discoverPrimaryKeys function returns the list of the foreign keys but it doesn't return any of the primary key. Do you have any idea about how to solve this problem? Thanks.

**Comment by davidcheung** [comment]
Issue addressed by PR #18, closing issue.
