### ISSUE TITLE
so confused - how does this lib hook into a loopback project?

### ISSUE THREAD

**Issue by the1mills** [strongloop/loopback-connector-postgresql#171]
I have installed this, using npm install:

```
 "dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-connector-postgresql": "^2.6.3",   <<<<
    "loopback-datasource-juggler": "^2.39.0",   <<<<
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^1.0.1"
  },
```

how can I implement automigration, without copying and pasting the code in this project? In other words, shouldn't "loopback-connector-postgresql" hook into my project and provide the `model.automigrate() `and `model.autoupdate()` functions?

Right now, my models are defined, but the automigrate function does not exist on the model.

For example:

```
module.exports = function(app) {

  var User = app.models.user;
  var Role = app.models.Role;
  var Project = app.models.project;
  var RoleMapping = app.models.RoleMapping;
  var Team = app.models.team;

   [Team, Project].forEach(item =>   item.automigrate());
```

>>> `Error: automigrate is not a function.`

Hope this makes sense.
-alex

**Comment by the1mills** [comment]
I think what should be mentioned is this:

```
 app.dataSources.psql.automigrate('project');
 app.dataSources.psql.automigrate('team');
```

could that be right?

**Comment by superkhau** [comment]
I think you should try going through the [Getting started](http://loopback.io/doc/en/lb2/Getting-started-with-LoopBack.html) sections first to understand how the connectors/datasources work together in the overall framework.

Some additional docs that could help:
- https://docs.strongloop.com/display/public/LB/Connect+your+API+to+a+data+source
- http://loopback.io/doc/en/lb2/Creating-a-database-schema-from-models.html

That said, please see https://github.com/strongloop/loopback/wiki/Questions. We reserve GitHub issues for actual project issues. Closing as there is nothing to resolve here.

**Comment by ORESoftware** [comment]
np thanks
