### ISSUE TITLE
count with where filter not working

### ISSUE THREAD

**Issue by adamwlarson** [strongloop/loopback-connector-postgresql#173]
I have a pretty simple query i'm trying to accomplish:
`UserMessageModel.count({where: {favorite: true, messageinstanceid: {inq: messageInstances}}})`

I am looking for all objects of type UserMessage with favorite set to true, that reference message instance in the array of messageincstances, which is just an array of numbers basically.

The problem is I always get back the count of all entries in that table in my unit tests the number is 4.

Simplifing the filter down to just this:
`UserMessageModel.count({where: {favorite: true}})`

Results in the same result in the promise of 4, when in the database there is clearly only one message that i have the favorite flag set on.

I've also tried with just using {favorite:true} without the wrapping {where:} and that didn't work either.

Any ideas on why this isn't working, or what I should be looking at to resolve the issue?

EDIT: I am on version 2.6.3 of the postgresql connector

EDIT 2: It does seem {where: } should not be included, if I run the same test I get a count of favorites correctly, but not filtered by the inq. Just to clarify messageinstance is a relation on the UserMessage that looks like this:

`  "relations": {
    "messageinstance": {
      "type": "belongsTo",
      "model": "MessageInstance",
      "foreignKey": ""
    }
  },`

In the database it creates a messageinstanceid that I assumed I could query against, but trying to query against messageinstance with the same improper results. So I think this might be a different problem now. Any ideas on what is wrong here?

EDIT 3: Doing a count with just messageinstanceid still yields a sum of all the entries in the table, there is definitely something wrong here...

EDIT 4:
Walking through the adapter I end up with a query stmt like this:
`"SELECT count(*) as \"cnt\" FROM \"public\".\"usermessage\" WHERE \"favorite\"=$1"`

`  var stmt = new ParameterizedSQL('SELECT count(*) as "cnt" FROM ' +
    this.tableEscaped(model));
  stmt = stmt.merge(this.buildWhere(model, where));
  stmt = this.parameterize(stmt);`

The where object has my inq object in there, but it is never added to the query before being executed. Is this a bug or a known limitation?

**Comment by skrenek** [comment]
You can log what queries your server is running by turning on the DEBUG flag for the Postgresql connector.  That may help troubleshoot.  

This is how I debug it: `DEBUG=loopback:connector:postgresql slc run`

[Loopback 2 docs for debug strings](http://loopback.io/doc/en/lb2/Setting-debug-strings.html)

**Comment by adamwlarson** [comment]
I did end up getting this to work

1. It looks like you can't include where and instead just include the filter, which is a little odd
2. I had to set my foreignkey to messageinstanceid instead of leaving it blank

`MessageModel.count({favorite: true, messageinstanceid: {inq: messageInstances}})`

This actually yields the proper results!

**Comment by shira6657** [comment]
> I did end up getting this to work
> 
> 1. It looks like you can't include where and instead just include the filter, which is a little odd
> 2. I had to set my foreignkey to messageinstanceid instead of leaving it blank
> 
> `MessageModel.count({favorite: true, messageinstanceid: {inq: messageInstances}})`
> 
> This actually yields the proper results!

thank you!
