### ISSUE TITLE
picking up "materialized views" vs. regular "views"?

### ISSUE THREAD

**Issue by the1mills** [strongloop/loopback-connector-postgresql#174]
I have some really sweet code that autogenerates .json models on our Loopback server based off of autodiscovery of structures in our Postgres DB, thanks to this library. Naturally, this keeps are server code in sync with the database, where we have a single source of truth. This is all very good.

However, it looks like my code does not pick up `materialized views` in the Postgres database, only `views`.

I am using

` ds.discoverModelDefinitions({views:true}, function (err, models) {});`

is there another method that I can use to discover materialized view DB structures as well as views in the DB?

E.g, autodiscovery with this lib does not seem to pick up "materialized views" as shown:

![mat_views](https://cloud.githubusercontent.com/assets/2148448/19128171/032ab332-8af7-11e6-866f-9f6593461491.png)

**Comment by the1mills** [comment]
ok I think I found the answer


// List database tables and/or views
`ds.discoverModelDefinitions({views: true, limit: 20}, function (err, models) {});`

**Comment by deepakrkris** [comment]
@the1mills at present loopback connectors do not support materialized views, and looks like only recent versions of postgresql support materialized views (9.3 and later)

**Comment by deepakrkris** [comment]
@the1mills this could only be considered for a stable major release later

**Comment by imravichaudhary** [comment]
+1

**Comment by pleivac** [comment]
+1

**Comment by saadismail** [comment]
> @the1mills at present loopback connectors do not support materialized views, and looks like only recent versions of postgresql support materialized views (9.3 and later)

Is this the case only for auto discovery? Or we can not even do read operations from materialized views?
