### ISSUE TITLE
Multiple foreignkeys possibility in Model Relation?

### ISSUE THREAD

**Issue by archenroot** [strongloop/loopback-connector-postgresql#183]
This is issue already asked on core loopback tree:
https://github.com/strongloop/loopback/issues/2080
 and on loopback-mysql-connector tree:
https://github.com/strongloop/loopback-connector-mysql/issues/150

I am in the same situation on Postgres database.

So basically achieve following in model definition:
"foreignKey":["id1","id2"]

**Comment by 0candy** [comment]
Closing this in favor of this https://github.com/strongloop/loopback-connector-postgresql/issues/184
