### ISSUE TITLE
Pool settings are not passed in if a connection url is used

### ISSUE THREAD

**Issue by gregdingle** [strongloop/loopback-connector-postgresql#185]
I wanted to change the size of the connection pool as described here: https://github.com/brianc/node-postgres . But the connector code drops those values here: https://github.com/strongloop/loopback-connector-postgresql/blob/ce2d382a0dfecdde234eaaeb01b8c75700f38bc4/lib/postgresql.js#L78 . 

It looks like an easy fix.

**Comment by superkhau** [comment]
@gregdingle Would you like to submit a PR?

**Comment by honestserpent** [comment]
@gregdingle I have this problem too, have you being able to successully change the connection pool size?

**Comment by ssh24** [comment]
This is issue has been resolved. Closing the ticket. Feel free to reopen if needed.
