### ISSUE TITLE
malformed REST api filter causing crash

### ISSUE THREAD

**Issue by karlmikko** [strongloop/loopback-connector-postgresql#19]
See https://github.com/strongloop/loopback/issues/338 for more information. 

When using "nin" and "inq" and not sending an array will cause an unhandled exception and crash nodejs.

**Comment by davidcheung** [comment]
Old issue from 2014, Looks like might be addressed by https://github.com/strongloop/loopback-datasource-juggler/commit/42c1ad3dcaebe385d2afe4c15409386cc3bf0aca 

and I tried to reproduce and cannot using api-explorer and able to catches and throws error
```json
{
  "error": {
    "name": "Error",
    "status": 400,
    "message": "The name property has invalid clause {\"inq\":\"\"}",
    "statusCode": 400,
    "stack": "Error: The name property has invalid clause {\"inq\":\"\"}\n    at ........"
  }
}
```

Closing issue
