### ISSUE TITLE
geo near filter is not supported

### ISSUE THREAD

**Issue by gregdingle** [strongloop/loopback-connector-postgresql#191]
Despite postgres having strong support for geo functions through the postgis extension, the `near` filter is not translated into SQL. This issue could also be related to #126.

The juggler then will calculate distance post-query, which is sub-optimal. See https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1794 . 

The mongodb connector has support: https://github.com/strongloop/loopback-connector-mongodb/blob/a44aec12572111d86d622c4083e9dbed78e739b0/lib/mongodb.js#L759

It looks like we just need to write a `buildNearFilter` function in `postgresql.js` that constructs the SQL functions: 
* postgis distance: http://postgis.net/docs/geometry_distance_knn.html
* postgis distance within: http://postgis.net/docs/ST_DWithin.html

**Comment by FreakTheMighty** [comment]
I think I've hit this issue. I didn't realize that distance in the `near` query is calculated in the application layer. It appears to be causing large CPU spikes.

Perhaps while this pull request is pending https://github.com/strongloop/loopback-connector-postgresql/pull/192, we can add a note that while `GeoPoint` is supported, the `near` query has limitations.

**Comment by gregdingle** [comment]
@FreakTheMighty : an intern on my team implemented a quick implementation of #192 . See https://github.com/gregdingle/loopback-connector-postgresql/compare/near-filter...Bubblyworld:near-filter . However, he did not implement test cases nor did I review the code yet. And he has gone back to school 🙃

**Comment by FreakTheMighty** [comment]
@gregdingle thank you. At very least this will be a very good place to start.
