### ISSUE TITLE
Support for full text search using to_tsvector and to_tsquery

### ISSUE THREAD

**Issue by imravichaudhary** [strongloop/loopback-connector-postgresql#202]
### Bug or feature request

- [x] Feature request

### Description of feature

Add mechanism to perform full text search for queries like 

```sql
SELECT
   streetName, streetType, city, province, postalCode
FROM
   address
WHERE 
   to_tsvector(concat_ws(' ', city, postalCode)) @@ to_tsquery('L9C:*')
```

**Comment by MohammedEssehemy** [comment]
I think this feature will be very helpful.
could you please reopen this.
