### ISSUE TITLE
postgres array functions

### ISSUE THREAD

**Issue by joeybenenati** [strongloop/loopback-connector-postgresql#206]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)
Is there any plan to incorporate the postgres array functions like array_append and array_remove? I noticed the mongo connector has the `allowExtendedOperators` property to include the array functions. if this is already possible, please advise. Ability to increment/decrement an integer property value would also be nice.

**Comment by ssh24** [comment]
This will need https://github.com/strongloop/loopback-connector-postgresql/issues/105 to be implemented first.
