### ISSUE TITLE
Timestamp always null.

### ISSUE THREAD

**Issue by Punkiebe** [strongloop/loopback-connector-postgresql#210]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

When selecting a row with a timestamp the timestamp is always null!

### Link to sample repo to reproduce issue (if bug)

I created a table with a timestamp as followed : 
start_time timestamp with time zone NOT NULL,;

In the loopback model this element configuration looks like : 
```
"startTime": {
      "type": "string",
      "required": true,
      "postgresql": {
        "columnName": "start_time",
        "dataType": "timestamp with time zone",
        "nullable": "NO"
      }
    },
```

### Expected result

"startTime": "2016-06-12 21:00:00"  (format it self isn't important, just that's filled in)

### Actual result (if bug)

"startTime": ""

### Additional information (Node.js version, LoopBack version, etc)

These are the loopback libs I'm using :
"loopback": "^3.0.0",
"loopback-boot": "^2.6.5",
"loopback-component-explorer": "^4.0.0",
"loopback-connector-postgresql": "^2.7.0",

The postgresql database is 9.2

**Comment by ssh24** [comment]
@Punkiebe I cannot reproduce this bug. Do you have a sample reproduction that I could follow?

Here is my sample reproduction and it works fine with postgresql `v2.7.0`.

**Model definition:**
```json
{
  "name": "Expense",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "Description": {
      "type": "string"
    },
    "Amount": {
      "type": "number"
    },
    "Stamp": {
      "type": "string",
      "postgresql": {
        "columnName": "stamp",
        "dataType": "timestamp with time zone",
        "nullable": "NO"
      }
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**Boot script:**
```javascript
'use strict';
var async = require('async');

module.exports = function(app) {
  var postgresDs = app.dataSources.postgresDs;
  var Expense = app.models.Expense;

  postgresDs.automigrate(function(err, result) {
    if (err) throw err;
    Expense.create([
      {
        Description: 'Expense 1',
        Amount: 12,
        Stamp: '1999-01-08 12:25:00',
      },
    ], function(err, result) {
      if (err) throw err;
      Expense.find(function(err, result) {
        if (err) throw err;
        console.log('Result: ' + JSON.stringify(result));
      });
    });
  });
};
```

**Output:**
```bash
Result: [{"Description":"Expense 1","Amount":12,"Stamp":"1999-01-08 12:25:00","id":1}]
```

**Comment by ssh24** [comment]
Closing this issue as it has been inactive. Feel free to reopen if needed.
