### ISSUE TITLE
Altering table from string to date through autoupdate failing

### ISSUE THREAD

**Issue by Strate** [strongloop/loopback-connector-postgresql#217]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
I ran into this issue while update from loopback 3.2.0 to loopback 3.3.0.

loopback@3.3.0 introduced change in builtin model Role. It changes type of "created" field from "string" to timestamp. Standard autoupdate function fails to alter db column with error "column "created" cannot be cast automatically to type timestamp with time zone"

**Comment by mikeodell77** [comment]
I am also having this issue.

**Comment by bajtos** [comment]
Hello, thank you for reporting the issue. I am afraid we may not have enough bandwidth to fix it right now. Did you managed to work around this problem by updating the columns from "string" to "timestamp" manually? Would you mind contributing the fix yourself?

**Comment by ssh24** [comment]
@Strate Thank you for reporting the issue. Do you have sample reproduction steps to reproduce this issue?

**Comment by ssh24** [comment]
This issue is fixed and should be available with the next released version of the connector. Thank you for your patience.
