### ISSUE TITLE
Running `autoupdate` is not idempotent

### ISSUE THREAD

**Issue by STRML** [strongloop/loopback-connector-postgresql#22]
I have noticed that `autoupdate` exhibits some very odd behavior. On base models (like User) where I have defined additional properties, those properties are removed if they exist, and added if they do not exist. This means the following can happen:

1. Add first custom field to a model, `A`
2. Run `autoupdate`. `A` is present.
3. Add another custom field, `B`.
4. Run `autoupdate`. `B` is present, `A` is not.
5. Run `autoupdate`. `A` is present, `B` is not. 

`automigrate` does work as expected, however.

**Comment by davidcheung** [comment]
Hi @STRML, @raymondfeng  trying to clean up old issues, as of now that ([docs](https://docs.strongloop.com/display/LB/Creating+a+database+schema+from+models)) the autoupdate schema comes with a table name I believe this is no longer an issue?

**Comment by STRML** [comment]
@davidcheung I am no longer able to replicate this issue, so I would call it safe to close.

**Comment by davidcheung** [comment]
Thanks @STRML, closing issue now.
