### ISSUE TITLE
Default for minimum pool size: After 10 Errors DB stops working

### ISSUE THREAD

**Issue by bobbysmith007** [strongloop/loopback-connector-postgresql#231]
### Bug or feature request

- [x] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)

After 10 sql errors, the application silently stops running any database code and will not execute sql any further with no indication of whats wrong. This occurs because without a minimum number of workers, the pool will wait till a worker is available, but never create any on its own.

Adding "min":3 to the datasource configuration (which is passed to pg-pool, which is passed to generic-pool) resolves this problem by assuring there are always at least 3  workers

### Link to sample repo to reproduce issue (if bug)

https://github.com/bobbysmith007/loopback-error-reproductions
`npm install .`
`npm run-script show-errors`

### Expected result

Running 15sql queries with errors from each

### Actual result (if bug)

Running 10sql queries with it silently never running the rest

### Additional information (Node.js version, LoopBack version, etc)

 * loopback: 3.4.0
 * nodejs :7.6.0

**Comment by ssh24** [comment]
@bobbysmith007 If you have a fix in place, would you mind creating a pull request?

**Comment by ssh24** [comment]
Should be fixed with https://github.com/strongloop/loopback-connector-postgresql/commit/0697d874083c6f13d17e6c4dd379c39ce5eef8c7. 

Closing this issue. Feel free to reopen if needed.
