### ISSUE TITLE
Support for HSTORE (Key-Value Data Type)

### ISSUE THREAD

**Issue by archenroot** [strongloop/loopback-connector-postgresql#232]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)
I am building configuration storage in PostgeSQL by using key-value store data type -> HSTORE. Is this kind of data type supported in loopback connector?

Update: I of course could implement keyvalue store with EAV entity model which loopback will definitelly work with without issues, but I am interested in HSTORE
### More about HSTORE
http://www.postgresqltutorial.com/postgresql-hstore/

**Comment by archenroot** [comment]
Some update as I have done some  research on this and this is in general related to key-value models from global perspective, of course PostgreSQL has its own specific implementation and SQL syntax to work with this kind of type, but otherwise it is fundamental funcitonality. I found discussion here:
https://github.com/strongloop/loopback/issues/2525

There is also already existing Redis connector:
https://loopback.io/doc/en/lb3/kv-redis-connector.html

As a temporary workaround I could implement full EAV in fully relational way and I am done:
https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model

Do you plan guys to implement this type for postgres in loopback in next few months or it is out of focus in the moment.

**Comment by ssh24** [comment]
Looked through the `hstore` data type and looks like it is something we can support in LoopBack. Added it as a feature request and have put it in our backlog.
