### ISSUE TITLE
can't create array type into postgre

### ISSUE THREAD

**Issue by luoboding** [strongloop/loopback-connector-postgresql#253]
i update loopback-connector-postgresql to v2.8 with npm,  i defined my model like this:
...
  "carousel": {
      "type": [
        "string"
      ]
    },
...
i post my data:

{
  "title": "string",
  "subTitle": "string",
  "thumbnail": "string",
  "carousel": [
    "string"
  ],
  "cd": 0
}

but i got an error:

{
    "error": {
        "statusCode": 500,
        "name": "error",
        "message": "malformed array literal: \"[\"string\"]\"",
        "length": 153,
        "severity": "ERROR",
        "code": "22P02",
        "detail": "\"[\" must introduce explicitly-specified array dimensions.",
        "file": "arrayfuncs.c",
        "line": "269",
        "routine": "array_in",
        "stack": "error: malformed array literal: \"[\"string\"]\"\n    at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:569:11)\n    at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:396:17)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:132:22)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:548:20)"
    }
}

**Comment by ssh24** [comment]
@luoboding Do you have a sample script to outline your issue?

I quickly wrote a script to describe your issue and works fine for me. I have a model `Teams` attached to a postgres datasource. Here is the model definition:
```json
{
  "name": "Teams",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "Name": {
      "type": "string",
      "required": true
    },
    "Manager": {
      "type": "string",
      "required": true
    },
    "Players": {
      "type": [
        "string"
      ]
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

And then I have a boot script:
```javascript
'use strict';
var async = require('async');

module.exports = function(app) {
  var postgresDs = app.dataSources.postgresDs;
  var Teams = app.models.Teams;

  postgresDs.automigrate(function(err, result) {
    if (err) throw err;
    Teams.upsert({
      Name: 'Liverpool Football Club',
      Manager: 'Jurgen Klopp',
      Players: ['Phillipe Coutinho', 'Roberto Firmino', 'Adam Lallana'],
    }, function(err, result) {
      if (err) throw err;
      console.log('Result: ' + require('util').inspect(result));
    });
  });
};
```

Here is the output which returns me all the list of players:
```bash
sakibs-mac:postgres-253 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
Result: { Name: 'Liverpool Football Club',
  Manager: 'Jurgen Klopp',
  Players: List [ 'Phillipe Coutinho', 'Roberto Firmino', 'Adam Lallana' ],
  id: 1 }
```

Here is my database query which returns the expected output:
```sql
ssh=# select * from public.teams;
          name           |   manager    |                        players                         | id
-------------------------+--------------+--------------------------------------------------------+----
 Liverpool Football Club | Jurgen Klopp | ["Phillipe Coutinho","Roberto Firmino","Adam Lallana"] |  1
```

Using postgresql version: `v2.8.1`

Please let me know if this helped you solve your issue.

**Comment by luoboding** [comment]
sorry, buddy, i can insert a record into postgre manually, but i can't insert a record in my loopback project,  i upgrade loopback-connector-postgresql to the latest version today, it works fine for me.

**Comment by AMHZR** [comment]
@luoboding can you further filter on to your query like Teams.find where player is "Phillipe Coutinho"

**Comment by jagdeepak-prat** [comment]
> sorry, buddy, i can insert a record into postgre manually, but i can't insert a record in my loopback project, i upgrade loopback-connector-postgresql to the latest version today, it works fine for me.

Hi, could you let me know what the problem was? I am facing the exact issue?
