### ISSUE TITLE
table type issue

### ISSUE THREAD

**Issue by jjhesk** [strongloop/loopback-connector-postgresql#260]
version: 3.0.1

![screen shot 2017-05-16 at 20 35 43](https://cloud.githubusercontent.com/assets/629338/26106080/4db17a50-3a77-11e7-898d-084ec079825a.png)
From the above key, user_from, is defined as a foreign key from another collection which is illustrated as below:
```

  "properties": {
...
"userFrom": {
      "type": "String",
      "required": false,
      "length": 24,
      "precision": null,
      "scale": null,
      "id": 1,
      "postgresql": {
        "columnName": "user_from",
        "dataType": "character varying",
        "dataLength": 24,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "YES"
      }
    },
...
}
...
  "relations": {
    "user": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "userFrom"
    }
```

why that key user_from has quotation?

**Comment by jjhesk** [comment]
#31 has the answer. Still it has inconsistency with other valuables.

**Comment by ssh24** [comment]
Not sure what the actual question in this issue is.

> why that key user_from has quotation?

**Comment by ssh24** [comment]
Closing this issue as there is no response from the user. Feel free to reopen if needed.
