### ISSUE TITLE
Out of range for type integer for bigint type

### ISSUE THREAD

**Issue by ozankasikci** [strongloop/loopback-connector-postgresql#269]
# Description/Steps to reproduce
With this property setup i can't get bigint working, it saves to database but loopback returns out of range error.

```javascript
"properties": {
    "bigint": {
      "type": "number",
      "postgresql": {
        "dataType": "bigint"
      }
    }
  }
```

Calling the update query this way: `app.dataSources.pg.connector.execute(query)`

# Expected result

expected to be able insert number bigger than 32 bit integer, but getting `error: value "20170706202" is out of range for type integer` even though the value gets inserted to the table.

So i guess it's an issue with postgresql connector, looks like it doesn't realize that the value type is bigint at runtime.

**Comment by ozankasikci** [comment]
oh it's my bad, migration didn't work and database field was still integer. closing this.

**Comment by FMGordillo** [comment]
Sorry, but where is this info in the documentation?

**Comment by tijanirf** [comment]
> Sorry, but where is this info in the documentation?

https://loopback.io/doc/en/lb3/PostgreSQL-connector.html

might be late, but hopefully make it easier for other people.

**Comment by arvindknit31** [comment]
I still am getting same error in loopback4 with postgres on windows 10, please suggest me what should i do? 

My package.json as follows

{
  "name": "smgmt",
  "version": "1.0.0",
  "description": "Store management",
  "keywords": [
    "loopback-application",
    "loopback"
  ],
  "main": "index.js",
  "engines": {
    "node": ">=8.9"
  },
  "scripts": {
    "build": "tsc",
    "build:watch": "tsc --watch",
    "clean": "rimraf dist *.tsbuildinfo",
    "pretest": "npm run clean && npm run build",
    "migrate": "node ./dist/migrate",
    "start": "npm run build && node -r source-map-support/register .",
    "prepare": "npm run build"
  },
  "repository": {
    "type": "git"
  },
  "author": "",
  "license": "",
  "files": [
    "README.md",
    "index.js",
    "index.d.ts",
    "dist",
    "src",
    "!*/__tests__"
  ],
  "dependencies": {
    "@loopback/boot": "^1.7.1",
    "@loopback/context": "^1.25.1",
    "@loopback/core": "^1.12.1",
    "@loopback/openapi-v3": "^1.11.0",
    "@loopback/repository": "^1.17.0",
    "@loopback/rest": "^1.25.1",
    "@loopback/rest-explorer": "^1.4.7",
    "@types/mocha": "^5.2.7",
    "loopback-connector-postgresql": "^3.8.1"
  },
  "devDependencies": {
    "@loopback/build": "^3.0.1",
    "@loopback/testlab": "^1.10.1",
    "@types/node": "^10.17.13",
    "rimraf": "^3.0.0",
    "source-map-support": "^0.5.16",
    "typescript": "~3.7.4"
  }
}
