### ISSUE TITLE
feature request for order by

### ISSUE THREAD

**Issue by ptrblgh** [strongloop/loopback-connector-postgresql#281]
## Target feature 

Source from: [https://www.postgresql.org/docs/9.6/static/queries-order.html](https://www.postgresql.org/docs/9.6/static/queries-order.html)

> [NULLS { FIRST | LAST }]
> The NULLS FIRST and NULLS LAST options can be used to determine whether nulls appear before or after non-null values in the sort ordering. By default, null values sort as if larger than any non-null value; that is, NULLS FIRST is the default for DESC order, and NULLS LAST otherwise.

## Use case 
Pagination and sorting on server-side (bandwith optimization). Most of the users except `NULL` values are at the end of the list in `DESC` direction and in the front in `ASC` direction (`NULL` values are lower than the exact values). The modification could give the opportunity to use this feature.

## Suggestion
Overriding the following function: [https://github.com/strongloop/loopback-connector/blob/master/lib/sql.js#L1182](https://github.com/strongloop/loopback-connector/blob/master/lib/sql.js#L1182)

In [https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/postgresql.js](https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/postgresql.js):
```js
/**
 * Build the ORDER BY clause
 * @param {string} model Model name
 * @param {string[]} order An array of sorting criteria
 * @returns {string} The ORDER BY clause
 */
SqlConnector.prototype.buildOrderBy = function(model, order) {
  if (!order) {
    return '';
  }
  var self = this;
  if (typeof order === 'string') {
    order = [order];
  }
  var clauses = [];
  for (var i = 0, n = order.length; i < n; i++) {
    var t = order[i].split(/[\s,]+/);
    if (t.length === 1) {
      clauses.push(self.columnEscaped(model, order[i]));
    } else if (t.length === 4) {
      clauses.push(self.columnEscaped(model, t[0]) + ' ' + t[1] + ' ' + t[2] + ' ' + t[3]);
    } else {
      clauses.push(self.columnEscaped(model, t[0]) + ' ' + t[1]);
    }
  }
  return 'ORDER BY ' + clauses.join(',');
};
```

I think this is not as easy as the above :). Any other suggestions/help appreciated.

**Comment by ssh24** [comment]
@ptrblgh Thank you for the feature request. Do you mind creating a pull request for this feature and then one of the admins can give their suggestions there?

**Comment by ptrblgh** [comment]
I have dived into deeper and my suggestion was wrong, unfortunately.

This modification request is out of the scope of this package. Reason:
[https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1531](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1531)

The loopback-datasource-juggler `_normalize` function needs to be changed to be able to handle this feature of Psql.

**Comment by ssh24** [comment]
@ptrblgh Not sure why the `_normalize` function needs to be changed to be able to handle this? Overriding **SqlConnector.prototype.buildOrderBy** should be sufficient. Or am I missing something?

**Comment by ptrblgh** [comment]
@ssh24 Yes, the SqlConnector.prototype.buildOrderBy gets a noramlized order parameter. Which means anything you pass after the order direction won't be processed. This line returns the final - normalized -
 order  by clause: [https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1531](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1531)

**Comment by ssh24** [comment]
@ptrblgh Yes, unfortunately that is the behaviour at the moment and it will be a breaking change in Juggler itself if this goes in.
