### ISSUE TITLE
double precision type bug

### ISSUE THREAD

**Issue by fosk06** [strongloop/loopback-connector-postgresql#282]
# Description/Steps to reproduce
I have a posteGresql database with a table "coordinate" with a field "lng" wich type is "double precision" .
there the request to create it
CREATE TABLE public.coordinate
(
    id uuid NOT NULL,
    event uuid,
    users uuid,
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    lng double precision NOT NULL,
    lat double precision NOT NULL
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

First  i created the models with a script using datasource.discoverModelDefinitions and
ds.discoverSchemas.
After some bug tracking, i found that the bug come for the model , with the fields "lng" and "lat" :
"lng": {
      "type": "Number",
      "required": true,
      "length": null,
      "precision": 53,
      "scale": null,
      "postgresql": {
        "columnName": "lng",
        "dataType": "double precision",
        "dataLength": null,
        "dataPrecision": 53,
        "dataScale": null,
        "nullable": "NO"
      }
    },
    "lat": {
      "type": "Number",
      "required": true,
      "length": null,
      "precision": 53,
      "scale": null,
      "postgresql": {
        "columnName": "lat",
        "dataType": "double precision",
        "dataLength": null,
        "dataPrecision": 53,
        "dataScale": null,
        "nullable": "NO"
      }
    }
then i'm trying to use the autoUpdate method in another script : 
var ds = loopback.createDataSource('postgresql', require('../datasources').dbpsql)
ds.autoupdate('coordinate', (err,result) => {
console.error(error)
})
I have then an error displayed : 
" error: syntax error at or near "(" "

# Expected result

# Additional information

darwin x64 7.8.0
├── loopback@3.9.0
├── loopback-boot@2.25.0
├── loopback-component-explorer@4.2.0
├── loopback-connector-postgresql@3.0.2

**Comment by ssh24** [comment]
@fosk06 I don't know what is causing this issue on your end. Maybe some syntax error on the script you wrote? 

I have tried on my end and cannot reproduce this.

**model-definition.json**
```json
{
  "name": "City",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "lng": {
      "type": "number",
      "postgresql": {
        "dataType": "double precision"
      }
    }, 
    "lat": {
      "type": "number",
      "postgresql": {
        "dataType": "double precision"
      }
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.postgresqlDs;
    var City = app.models.City;

    db.automigrate(function(err) {
        if (err) throw err;
        console.log('\nAutomigrate completed');

        db.discoverModelProperties('city', function(err, props) {
            if (err) throw err;
            console.log('\nModel properties: ' + util.inspect(props));
        });
    });
};
```

**output**
```bash
sakibs-mac:postgresql-282 ssh$ node .
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer

Automigrate completed

Model properties: [ { owner: 'public',
    tableName: 'city',
    columnName: 'name',
    dataType: 'text',
    dataLength: null,
    dataPrecision: null,
    dataScale: null,
    nullable: 'YES',
    type: 'String' },
  { owner: 'public',
    tableName: 'city',
    columnName: 'lng',
    dataType: 'double precision',
    dataLength: null,
    dataPrecision: 53,
    dataScale: null,
    nullable: 'YES',
    type: 'Number' },
  { owner: 'public',
    tableName: 'city',
    columnName: 'lat',
    dataType: 'double precision',
    dataLength: null,
    dataPrecision: 53,
    dataScale: null,
    nullable: 'YES',
    type: 'Number' },
  { owner: 'public',
    tableName: 'city',
    columnName: 'id',
    dataType: 'integer',
    dataLength: null,
    dataPrecision: 32,
    dataScale: 0,
    nullable: 'NO',
    type: 'Number' } ]
```

**database output**
```bash
testdb=# \d City;
                              Table "public.city"
 Column |       Type       |                     Modifiers
--------+------------------+---------------------------------------------------
 name   | text             |
 lng    | double precision |
 lat    | double precision |
 id     | integer          | not null default nextval('city_id_seq'::regclass)
Indexes:
    "city_pkey" PRIMARY KEY, btree (id)
```

**Comment by fosk06** [comment]
I have a field like this : 
"lng": {
      "type": "Number",
      "required": true,
      "length": null,
      "precision": 53,
      "scale": null,
      "postgresql": {
        "columnName": "lng",
        "dataType": "double precision",
        "dataLength": null,
        "dataPrecision": 53,
        "dataScale": null,
        "nullable": "NO"
      }
    },
It's seems that the "dataPrecision":53 is the source of the bug, if i remove it it's working.
The fields has been set by the ds.discoverSchemas ( reverse from existing database) .

**Comment by fosk06** [comment]
I your example you used the automigrate method, in my case i used the autoupdate method

**Comment by fosk06** [comment]
this is my auto update script : 
var path = require('path')
var loopback = require('loopback')
var outputPath = path.resolve(__dirname, '..', '..', 'common', 'models')
var ds = loopback.createDataSource('postgresql', require('../datasources').dbpsql)
let model = require(path.resolve(outputPath, 'coordinates.json'))
ds.createModel(model.name, model.properties, model.options)
ds.autoupdate(model.name, function (err, result) {
  console.error(err)
  console.log(result)
})

**Comment by ssh24** [comment]
@fosk06 This is an excellent catch. I have submitted a pull request for the fix.
