### ISSUE TITLE
GePoint create ERROR

### ISSUE THREAD

**Issue by mkzaker** [strongloop/loopback-connector-postgresql#29]
hi
When I want to create a model that includes the GeoPoint Type , getting the following error
{
  "error": {
    "name": "error",
    "status": 500,
    "message": "invalid input syntax for type point: \"{\"lat\":59.6150515,\"lng\":36.2876827}\"",
    "length": 122,
    "severity": "ERROR",
    "code": "22P02",
    "file": "geo_ops.c",
    "line": "1820",
    "routine": "point_in",
    "stack": "error: invalid input syntax for type point: \"{\"lat\":59.6150515,\"lng\":36.2876827}\"\n    at Connection.parseE (/home/zaker/proj/markmap/node_modules/loopback-connector-postgresql/node_modules/pg.js/lib/connection.js:526:11)\n    at Connection.parseMessage (/home/zaker/proj/markmap/node_modules/loopback-connector-postgresql/node_modules/pg.js/lib/connection.js:356:17)\n    at Socket.<anonymous> (/home/zaker/proj/markmap/node_modules/loopback-connector-postgresql/node_modules/pg.js/lib/connection.js:105:22)\n    at Socket.emit (events.js:95:17)\n    at Socket.<anonymous> (_stream_readable.js:764:14)\n    at Socket.emit (events.js:92:17)\n    at emitReadable_ (_stream_readable.js:426:10)\n    at emitReadable (_stream_readable.js:422:5)\n    at readableAddChunk (_stream_readable.js:165:9)\n    at Socket.Readable.push (_stream_readable.js:127:10)"
  }
}
what is the problem?

**Comment by slively** [comment]
@raymondfeng That fixed my issue, I'm currently using the feature/add-geopoint-support branch in my project. A merge would be awesome, thank you!

**Comment by davidcheung** [comment]
> @raymondfeng That fixed my issue, I'm currently using the feature/add-geopoint-support branch in my project. A merge would be awesome, thank you!

Trying to clean up old issues, looks like it has been fixed a year ago :p  Closing issue now.
