### ISSUE TITLE
Postgis support ?

### ISSUE THREAD

**Issue by Vincz** [strongloop/loopback-connector-postgresql#299]
Hi! I'm considering loopback as a framework for my next api but I need support for some Postgis features.
I was wondering if this connector supports the postgis features or, if it does not, if it's easy to use native SQL query to retrieve models, etc...
For example, how could we define a geography Point colum
how can we insert data in it with models
how to query on it

I tried something like this as a property for a model:

    "location": {
        "type": "geopoint",
         "required": true,
         "postgresql": {
             "columnName": "location",
              "dataType": "geography(Point,4326)",
              "nullable": "YES"
          }
    }

if it does generate the database schema properly, I'm not able to create model, as I get the following pg error:

column "location" is of type geography but expression is of type point

Is there any simple way to define own type and query them ?

Thanks !

**Comment by ewrayjohnson** [comment]
PostgreSQL Point types are supported by the [PostgreSQL connector](https://loopback.io/doc/en/lb3/PostgreSQL-connector.html) using the [Geopoint data type](https://loopback.io/doc/en/lb3/Geotype.html).  Other Geometry types are not supported.  Only rudimentary proximity searches are supported: [near](https://loopback.io/doc/en/lb3/Where-filter.html#near), [ordering and limiting by distance](https://loopback.io/doc/en/lb3/Where-filter.html#near-ordering-andlimiting-by-distance).
