### ISSUE TITLE
error: relation "user" already exists

### ISSUE THREAD

**Issue by doowb** [strongloop/loopback-connector-postgresql#307]
# Description/Steps to reproduce

I'm running `ds.autoupdate();` on each of my datasources in a boot script to ensure the tables are created for postgresql. The first time I start the server, I'm getting the following error and the server crashes:

> error: relation "user" already exists

Once I start it again the `autoupdate` runs fine. 

# Link to reproduction sandbox
 
When first seeing this, my setup was the same as the [user management example](https://github.com/strongloop/loopback-example-user-management)

# Expected result

The `ds.autoupdate()` runs without the error the first time.

# Additional information

The following system information is from my machine (which I used initially and connected to a PostgreSQL database hosted with Heroku).

```
darwin x64 8.4.0
├── loopback@3.16.2
├── loopback-api-definition@3.1.0
├── loopback-boot@2.27.0
├── loopback-component-explorer@5.2.0
├── loopback-connector-postgresql@3.1.0
```

The second time it happened was on a different database hosted on Heroku but from the Heroku server.

Also, this is the boot script I'm using for looping over the datasources and calling `autoupdate`:

```js
module.exports = async function(server) {
  const dataSources = Object.keys(server.dataSources);
  const len = dataSources.length;
  for (let i = 0; i < len; i++) {
    const name = dataSources[i];
    const ds = server.dataSources[name];
    const isActual = await ds.isActual();
    if (isActual) {
      console.log(`datasource "${name}" is up to date.`);
      continue;
    }
    await ds.autoupdate();
    console.log(`datasource "${name}" updated.`);
  }

  return Promise.resolve();
};
```

I'm noticing that I get duplicate datasource names from the `console.log` statements that only vary by capitalization, however, the error occurs when running the first datasource `db` and not getting to the second datasource `Db`.

**Comment by qlerebours** [comment]
@doowb did you find a solution to your issue ?

**Comment by doowb** [comment]
@qlerebours no and I'm no longer using this so I don't know if it's been resolved.
