### ISSUE TITLE
wrong schema discovered

### ISSUE THREAD

**Issue by punund** [strongloop/loopback-connector-postgresql#32]
If schema is given in a datasource definition, `discoverSchema` still returns `{"schema": "public"...` in discovered model.

**Comment by mrkswrnr** [comment]
Best workaround I found for defining a different schema than public was to alter the datasource user:
`ALTER ROLE your_datasource_username SET search_path = your_schema`

**Comment by ssh24** [comment]
The schema specified in the datasource definition has nothing to do with the schemas returned. You can specify the schema on the `discoverSchema` function.

```
ds.discoverSchema(tableName, {schema: <my_schema>}, cb);
```

For more info on the apidocs for the `discoverSchema` function, visit [here](https://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-discoverschema).

Closing this story as resolved. Feel free to reopen if needed.
