### ISSUE TITLE
Setting maximum number of clients in the connection pool isn't working

### ISSUE THREAD

**Issue by al-k21** [strongloop/loopback-connector-postgresql#326]
Seems like setting `"max": 2` is not setting a Maximum number of clients in the connection pool to 2.

## Description/Steps to reproduce

This is my data source:
```json
{
  "PostgressqlDS": {
    "url": "<URL>",
    "name": "PostgressqlDS",
    "user": "",
    "connector": "postgresql",
    "max": 2
  }
}
```

This is an error I am getting:
```
{ error: too many connections for role "scluhkce"
    at Connection.parseE (/Users/oleksandrkushchak/Code/module-curation-api/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/Users/oleksandrkushchak/Code/module-curation-api/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/Users/oleksandrkushchak/Code/module-curation-api/node_modules/pg/lib/connection.js:113:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:276:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onread (net.js:630:20)
  name: 'error',
  length: 110,
  severity: 'FATAL',
  code: '53300',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'miscinit.c',
  line: '559',
  routine: 'InitializeSessionUserId' }
```

## Expected result

I would expect that setting `"max": 2` would only allow 2 concurrent connections. https://github.com/strongloop/loopback-connector-postgresql#properties

## Additional information

*NOTE:* I am using a free bluemix instance that only allows 5 connection at the same time.

**Comment by raymondfeng** [comment]
Hmm, we pass `max` to pg.Pool() and it should be honored. See https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/postgresql.js#L81. Do you have more than one instances of the datasource being active?

**Comment by al-k21** [comment]
I keep hitting this issue when trying to build the tables like this:
```js
let app = require('./server');
let datasources = Object.keys(app.dataSources); cb = '';
async function update() {
  for (let i in datasources) {
    let dsName = datasources[i];
    let ds = app.dataSources[dsName];
    try {
      await ds.autoupdate();
      console.log(`DS: ${dsName} is updated.`);
    } catch (e) {
      throw e;
    }
  }
}
update();
```
Could you help resolve this? @raymondfeng

**Comment by raymondfeng** [comment]
In your code, you should call `await ds.disconnect()` after autoupdate to release connections. Please note each datasource has its own pool of connections.

**Comment by al-k21** [comment]
Thanks, @raymondfeng! I have updated the code but unfortunately, it still fails.

**Comment by al-k21** [comment]
I had an older version of a `loopback-connector` intalled:

<img width="708" alt="image" src="https://user-images.githubusercontent.com/29542357/40452822-183d53f6-5edb-11e8-979d-26ade5344b4a.png">

Updating `loopback-connector-postgresql` has helped:
```diff
-    "loopback-connector-postgresql": "^2.9.0",
+    "loopback-connector-postgresql": "3.3.1",
````
Thanks @raymondfeng for helping figuring this out.

**Comment by dhmlau** [comment]
Closing this as latest version postgresql connector solved the problem.
