### ISSUE TITLE
Type 'double precision' is mapped to String

### ISSUE THREAD

**Issue by ataft** [strongloop/loopback-connector-postgresql#346]
On [line 144](https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/discovery.js#L144) of discovery.js, dataType "real" and "double precision" are changed to "float", but buildPropertyType has no case for "FLOAT". 

I created the the following pull request to simply add a case statement for 'FLOAT':
https://github.com/strongloop/loopback-connector-postgresql/pull/345

**Comment by dhmlau** [comment]
Moving it to `In progress` as PR #345 is up.

**Comment by dhmlau** [comment]
Closing this as PR #345 has been merged.
