### ISSUE TITLE
Foreign Key Constraint 

### ISSUE THREAD

**Issue by elv1s** [strongloop/loopback-connector-postgresql#348]
Foreign Key Constraint in Postgres connector

Similar to the MySQL data connector, it would be great if the Postgres connector supported Foreign Key Constraints defined in LoopBack models. This would enforce referenced object to exist before adding relationship, and prevent deletion if the object is being referenced.

The `foreignKeys` would be the same top level property for models compatible with MySQL

```json
{
  "name": "Project",

  "relations": {
    "account": {
      "type": "belongsTo",
      "model": "Account",
      "foreignKey": "accountId",
      "primaryKey": "id"
    }
  },

  "foreignKeys": {
    "accountId": {
      "name": "accountId",
      "foreignKey": "accountId",
      "entityKey": "id",
      "entity": "Account"
    }
  }
}
```

# Additional information

For related MySQL issue see: https://github.com/strongloop/loopback-connector-mysql/issues/294

**Comment by elv1s** [comment]
If this is something worth taking I can work on this.

**Comment by YuriScarbaci** [comment]
@elv1s I would love to see this feature working to be honest, and I also think this make sense since the MySQL connector does have this feature working.

**Comment by dhmlau** [comment]
I think we do the foreign key constraint a bit differently in LB4.  Are you using LB4 or LB3?  If it's LB4, github supports transferring issue to another repo or I can move it for you as well. 

cc @b-admike @raymondfeng

**Comment by dhmlau** [comment]
Yes, it's the same connector.  IIRC, there's some constraint done at the Repository level for LoopBack 4, that's why I asked.  I'll leave this issue in the current repo then.

**Comment by dhonig** [comment]
@elv1s my project needs this as well.  Happy to help test.  +1 for loopback 3

**Comment by raymondfeng** [comment]
FK constraints can be potentially enforced by the database if `automigrate` creates corresponding DB definitions. For example - https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/migration.js

**Comment by elv1s** [comment]
The same models used to create FKs in MySQL don't seem to be creating constraints in postgres. (I had to use `autoupdate` to create the keys in MySQL)

@raymondfeng I don't see which line in the postgres connector code the FK constraint is created from the model relationship.

**Comment by elv1s** [comment]
any update on this? Thanks!

**Comment by codepushr** [comment]
I'm also interested in this... so if I understood this correctly the model root node 'foreignKeys' is only working with the mySQL connector, not with postgres?

**Comment by bvanleeuwen1995** [comment]
I'm also interested in this, this is the only thing that is missing from the postgres connector at the moment if you ask me. It leaves a lot of garbage data at the moment behind in our DB which required the need of various hooks to clear it all up.

**Comment by elv1s** [comment]
I should have a pull request ready tomorrow

**Comment by codejamninja** [comment]
Is it safe to manually create foreign keys in postgres?

**Comment by elv1s** [comment]
@codejamninja it seems safe in my testing. What are your concerns?

There is an order that is required when creating and dropping tables. Parent tables must exist before applying the constraint.

**Comment by codejamninja** [comment]
I was told it's poor database design to not use a foreign key in Postgres with cascading rules that clean up any dependent tables. Is this true? If so, why is it not implemented in this library?

**Comment by elv1s** [comment]
I think it should be up to the developer if deleting a related record should automatically delete any associated records, or to return an error indicating the record can't be deleted until other records that have a reference to it are deleted.

We can give the option when creating the FK to add `ON DELETE CASCADE`

**Comment by codejamninja** [comment]
How do you do that?

**Comment by elv1s** [comment]
It would need to be added as an option, likely in a followup PR. Maybe something like
```json
{
  "name": "Project",
  "foreignKeys": {
    "accountId": {
      "name": "accountId",
      "foreignKey": "accountId",
      "entityKey": "id",
      "entity": "Account",
      "cascade": true <-- enable cascade delete
    }
  }
}
```

**Comment by dhmlau** [comment]
Fixed via https://github.com/strongloop/loopback-connector-postgresql/pull/356.

**Comment by FournetThomas** [comment]
Did that cascade delete feature have been added in the project ?

**Comment by pdarii** [comment]
Hi, any updates on cascade deleting?

**Comment by praneshvrp1396** [comment]
Any update on onDelete cascade?

**Comment by kezek** [comment]
Any updates on this ?

**Comment by clearhost-cmd** [comment]
Any updates?
