### ISSUE TITLE
Multiple foreign keys on same model

### ISSUE THREAD

**Issue by pharindoko** [strongloop/loopback-connector-postgresql#359]
# Description/Steps to reproduce
Create a model having to foreignKeys in options e.g.: 

````
  "options": {
    "idInjection": false,
    "validateUpsert": true,
    "foreignKeys": {
      "fk_vehicles_vehicleMasterId": {
        "name": "fk_vehicles_vehicleMasterId",
        "entity": "VehicleMaster",
        "entityKey": "VIN",
        "foreignKey": "vehicleMasterId"
      },
      "fk_vehicles_vehicleRegistryId": {
        "name": "fk_vehicles_vehicleRegistryId",
        "entity": "VehicleRegistry",
        "entityKey": "licenseNumber",
        "foreignKey": "vehicleRegistryId"
      }
    }
  },
````

When you do autoupdate first it will create the Constraints correctly.
When you do a second autoupdate it will try to drop the constraints first (I think this is standard behaviour and it will try to recreate them right ?)

When it tries to alter the table with following command
```
SQL: ALTER TABLE "public"."vehicles" DROP CONSTRAINT "fk_vehicles_vehicleMasterId"  DROP CONSTRAINT "fk_vehicles_vehicleRegistryId"
```

The error output is:
```
error: syntax error at or near "DROP"
```
as this is no correct sql command - second drop statement cannot be included

# Expected result

Having separated sql commands for each DROP CONSTRAINTS statement

**Comment by pharindoko** [comment]
I`ve found the reason....

Migration.js - getDropForeignKeys Method - line 549 - no comma in between DROP CONSTRAINT statements..
This fixes the issue. I`ll create a PR...

```
        if (needsToDrop) {
          console.log('test' + fk.fkName);
          sql.push('DROP CONSTRAINT ' + self.escapeName(fk.fkName)+ '');
          removedFks.push(fk); // keep track that we removed these
        }
        if (sql.length > 0) {
          sql = [sql.join(', ')];
        }
      });
```

**Comment by elv1s** [comment]
this can be closed. Fix was merged in https://github.com/strongloop/loopback-connector-postgresql/pull/361

**Comment by raymondfeng** [comment]
@elv1s Thanks!
