### ISSUE TITLE
Unhandled error in POST /users: 500 error: malformed array literal: "0"

### ISSUE THREAD

**Issue by salomaosnff** [strongloop/loopback-connector-postgresql#370]
# Description/Steps to reproduce
1. Create a datasource with loopback-connector-postgresql
2. Create a Entity Model
3. Create a DefaultCrudRepository
4. Create a Default Crud Controller
5. Make a POST request for the controller entrypoint

# Link to reproduction sandbox

# Expected result
The data must be written to the database without any error

# Additional information
OS: Linux Ubuntu
Node v8.10.0
NPM v6.4.1
PostgreSQL 10.6
Installed Packages
├── @loopback/boot@1.0.14
├── @loopback/context@1.6.0
├── @loopback/core@1.1.7
├── @loopback/openapi-v3@1.2.3
├── @loopback/repository@1.1.7
├── @loopback/rest@1.7.0
├── @loopback/rest-explorer@1.1.10
├── @loopback/service-proxy@1.0.9
└── loopback-connector-postgresql@3.6.0

**Comment by dhmlau** [comment]
@salomaosnff , could you please share your model that can reproduce this issue?  It would be good if you could include a sample of the POST request as well. Thanks.

**Comment by salomaosnff** [comment]
user.model.ts
```typescript
import { Entity, model, property } from '@loopback/repository';

@model({settings: {"strict":false}})
export class User extends Entity {
  @property({
    type: 'number',
    id: true,
    generated: true
  })
  id?: number;

  @property({
    type: 'string',
    required: true,
  })
  email: string;

  @property({
    type: 'string',
    required: true,
  })
  password: string;
  // Define well-known properties here

  // Indexer property to allow additional data
  [prop: string]: any;

  constructor(data?: Partial<User>) {
    super(data);
  }
}

```

POST /users
Content-Type: application/json
```
{
  "email": "foo@bar.com",
  "password": "foobar"
}
```

**Comment by dhmlau** [comment]
@salomaosnff , sorry about the delay.  I think your id cannot be optional. It should be:
```
@property({
    type: 'number',
    id: true,
    generated: true
  })
  id: number; //change it to be not optional
```
I've created this repo before to test a few things, you can check it out. 
https://github.com/dhmlau/loopback4-example-todo-customized#how-to-auto-generate-the-ids

Hope it helps.

**Comment by salomaosnff** [comment]
I was able to solve the problem by changing the version of PostgreSQL to version 9, is there any support for the latest versions of PostgreSQL?

**Comment by dhmlau** [comment]
Is there a particular version you're looking for? 
I tried it with the PostgreSQL docker image, and it says it's in 11.2.

**Comment by dhmlau** [comment]
@salomaosnff, is there anything i can help you regarding this ticket? If not, I'm going to close it. Thanks.
