### ISSUE TITLE
update the "debug" dependency?

### ISSUE THREAD

**Issue by noctifer20** [strongloop/loopback-connector-postgresql#373]
# Description/Steps to reproduce

package.json dependencies are 
```json
"debug": "^4.1.1",
"loopback-connector-postgresql": "^3.5.0"
```
On  `npm install` It installs 2 `debug` modules:
- `debug@4.1.1` in main `node_modules` directory
- nested `debug@3.2.6` in `node_modules/loopback-connector-postgresql/node_modules`

It creates problems with application process management as all packages not using same `debug` module instance

Is it possible to update `debug` dependency to 4.1.1 as it seems, that there are no breaking changes?

# Additional information
`win32 x64 11.9.0`
```
+-- @loopback/authentication@1.1.2
+-- @loopback/boot@1.2.1
+-- @loopback/context@1.11.0
+-- @loopback/core@1.4.1
+-- @loopback/openapi-v3@1.3.5
+-- @loopback/repository@1.4.1
+-- @loopback/rest@1.10.2
+-- @loopback/rest-explorer@1.1.16
+-- @loopback/service-proxy@1.1.4
+-- loopback-4-accesscontrol@1.0.0
+-- loopback-connector-postgresql@3.6.1
```

**Comment by dhmlau** [comment]
@noctifer20, it makes sense.  Would you like to submit a PR? Thanks.

**Comment by noctifer20** [comment]
Thanks for response!
> Would you like to submit a PR?

Sure.

**Comment by dhmlau** [comment]
PR #374 has landed.  @noctifer20, thanks again for your contribution. I'm closing this issue as done.
