### ISSUE TITLE
tls connections

### ISSUE THREAD

**Issue by devbytom** [strongloop/loopback-connector-postgresql#388]
# Description

attempting to connect to a ibmcloud postgres database i found the following documentation explaining what the ssl property should be fed.

![image](https://user-images.githubusercontent.com/11949221/62724634-d135e700-b9e9-11e9-9d12-13426a54d275.png)

source: https://loopback.io/doc/en/lb2/PostgreSQL-connector.html

according to this, i should mount a settings object similar to the tls.connect() inside the official nodejs docs.

https://nodejs.org/dist/latest-v4.x/docs/api/tls.html#tls_tls_connect_options_callback

after a tough troubleshooting time, i messaged @raymondfeng  and he helped me to find out that the settings object was straightly assigned to the `pg` module Pool settings.

therefore, a pertinent setting would have to fit the pg module settings, even the ssl one as the following:

```

const ssl = {
    rejectUnauthorized: false,
    ca: fs.readFileSync(process.env.PG_ALPHA_SSL_PATH).toString('utf8'),
  };

  const settings = {
    db: {
      name: 'db',
      connector: pgConnector,
      hostname: process.env.PG_ALPHA_HOSTNAME,
      database: process.env.PG_ALPHA_DATABASE,
      schema: process.env.PG_ALPHA_SCHEMA,
      username: process.env.PG_ALPHA_USER,
      password: process.env.PG_ALPHA_PASSWORD,
      port: parseInt(process.env.PG_ALPHA_PORT),
      ssl,
    },
    dbProd: {
      name: 'dbProd',
      connector: pgConnector,
      hostname: process.env.PG_PROD_HOSTNAME,
      database: process.env.PG_PROD_DATABASE,
      schema: process.env.PG_PROD_SCHEMA,
      username: process.env.PG_PROD_USER,
      password: process.env.PG_PROD_PASSWORD,
      port: parseInt(process.env.PG_PROD_PORT),
      ssl,
    },
  };

  const models = app.models;

  const dbProd = new DataSource(pgConnector, settings.dbProd);

```

**Comment by dhmlau** [comment]
@devbytom, thanks for sharing the info. 
As the purpose of this github issue, are you suggesting the documentation should be updated or something we need to fix?  

cc @raymondfeng

**Comment by devbytom** [comment]
@dhmlau i believe the documentation should explicit that the connector accepts the same options body as the node-postgres's one. that would've saved me and perhaps anybody else a couple of hours of troubleshooting.
