### ISSUE TITLE
Dependency version error

### ISSUE THREAD

**Issue by DmitryPoluyan** [strongloop/loopback-connector-postgresql#395]
# Description/Steps to reproduce
Hello. I am using "loopback-connector-postgresql": "3.7.0"
![image](https://user-images.githubusercontent.com/16204601/65322854-927e7980-dbb0-11e9-8d6c-ee4f9a26c9d0.png)
Today the version of strong-globalize has changed to 5.0.2. 
I use: "node": "6.9.2". So I have not packge-lock.js 

And I have the error when I start application:
/node_modules/os-locale/index.js:27
async function getLocales() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

Can you set fix version or help me somehow?

**Comment by dhmlau** [comment]
@DmitryPoluyan , would you be able to update your Node.js version?  
Reading [this thread on StackOverflow](https://stackoverflow.com/questions/37815790/syntaxerror-unexpected-token-function-async-await-nodejs), it says:
> Async functions are not supported by Node versions older than version 7.6.
http://kangax.github.io/compat-table/esnext/

Please be reminded that Node.js 6 has reached end of life: https://github.com/nodejs/Release, so it's recommended that you're updating your Node.js version anyway.

**Comment by DmitryPoluyan** [comment]
Yes. I have created npm-shrinkwrap with working for me node_modules and updated application to 8.16.1 node version and npm 6.4.1 which support package.lock.json and npm-shrinkwrap.json .
