### ISSUE TITLE
invalid input syntax for type json when use repository.updateById()

### ISSUE THREAD

**Issue by zzhenryquezz** [strongloop/loopback-connector-postgresql#396]
# Description/Steps to reproduce

When the dataType is JSON or JSONB and use repository.updateById() can't add the new array in database, but work normaly if use repository.replaceById()

Model: 
```
@property({
    type: 'array',
    itemType: 'object',
    postgresql: {
      dataType: 'jsonb'
    },
    required: true,
  })
  test: AnyObject[];
```
Controller: 
```
await this.testRepository.updateById(test_id, test);
```
Response:
```
invalid input syntax for type json
```
# Sandbox
https://github.com/zzhenryquezz/bug-update-arrya-jsonb

# Expected result
Update the array jsonb in Postgres Database

# Additional information
Maybe is something related in the parse to JSON of the method updateById()

# Edit: Steps to reproduce

1 - First config a postgres database in json connector

![example-dbconfig](https://user-images.githubusercontent.com/43827016/70124725-2a3e2080-1654-11ea-8414-b476db228486.png)

2 - Create a dummy data for the tests using the POST endpoint

![example-post](https://user-images.githubusercontent.com/43827016/70124764-3f1ab400-1654-11ea-92bc-b2fc49878934.png)

3 - Try update one entity using the PATH endpoint
![example-update](https://user-images.githubusercontent.com/43827016/70124837-5fe30980-1654-11ea-90ea-2993fde76cf7.png)

4 - This will trigger a Internar server error and also a error log in console
![example-console-error](https://user-images.githubusercontent.com/43827016/70124881-77ba8d80-1654-11ea-9fc3-caa5271f99f8.png)

**Comment by dhmlau** [comment]
@raymondfeng @bajtos, it seems like a bug to me if it's working fine with `repository.replaceById()` but not `repository.updateById()`. What do you think?

**Comment by bajtos** [comment]
> It seems like a bug to me if it's working fine with repository.replaceById() but not repository.updateById(). 

Possibly.

> Sandbox
> https://github.com/zzhenryquezz/bug-update-arrya-jsonb

@zzhenryquezz Thank you for creating the reproduction app. I quickly skimmed through the code, but I don't see how are you invoking `replaceById` and `updateById` methods. What are the steps to reproduce the problem using your app?

**Comment by zzhenryquezz** [comment]
Hi @bajtos I add the steps to reproduce in the issue description, should be more clear now.

**Comment by bajtos** [comment]
> I add the steps to reproduce in the issue description, should be more clear now.

Thank you @zzhenryquezz for the update. I am afraid I don't see those steps anywhere in your example app. Are you referring to `Steps to reproduce` section in the issue description?

**Comment by zzhenryquezz** [comment]
@bajtos On this page, hover up and see, this is the last section of the comment.
