### ISSUE TITLE
commit or rollback a transaction does not delete the connection's reference 

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-postgresql#411]
## Steps to reproduce

Originated from https://github.com/strongloop/loopback-next/pull/4474
To reproduce it, remove the special check for postgresql on [this line](https://github.com/strongloop/loopback-next/pull/4474/files#diff-5b8b9c9868638cbf9ea2dfbbee7b1593R80), and run the tests.

You will see `isActive` returns true when run the shared tests with postgresql.

The reason is explained in https://github.com/strongloop/loopback-next/pull/4474#issuecomment-577886571:

`packages/repository` has a juggler and its loopback-connector as dep, and juggler's Transaction mixin is applied to its lb-connector's Transaction. 
So tests in mysql [creates transaction](https://github.com/strongloop/loopback-connector/blob/master/lib/transaction.js#L110) with the Transaction that has mixin's overriden prototype methods.

While for postgresql, **[`create transaction`](https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/transaction.js#L31) uses the Transaction in `acceptance/repository-postgresql`'s dependency, which doesn't have the juggler's Transaction mixin applied.** And therefore won't [delete the connection reference for `tx`](https://github.com/strongloop/loopback-datasource-juggler/blob/251ced811b80177f47efb6a3270ed6d279263c46/lib/transaction.js#L151)

The transaction's design in this connector changes after PR https://github.com/strongloop/loopback-connector-postgresql/pull/230, I couldn't recall what issue it fixed exactly, but now it looks like returning a new transaction instead of a connection causes inconsistency between postgresql and other connectors, which results in juggler's mixin functions like `commit` are not applied on that transation's prototype.

## Current Behavior

See ^

[`create transaction`](https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/transaction.js#L31) uses the Transaction in `acceptance/repository-postgresql`'s dependency, which doesn't have the juggler's Transaction mixin applied. And therefore won't [delete the connection reference for `tx`](https://github.com/strongloop/loopback-datasource-juggler/blob/251ced811b80177f47efb6a3270ed6d279263c46/lib/transaction.js#L151)

## Expected Behavior

Postgresql connector should have consistent behaviour as other connectors on the transaction:

- `beginTransaction` should return connection instead of creating a transaction then return it
- The original issue fixed by https://github.com/strongloop/loopback-connector-postgresql/pull/230 should be revisited, and replaced with another solution that doesn't introduce the inconsistent behaviour.

**Comment by Tronix117** [comment]
What is the status of the issue ?
