### ISSUE TITLE
Connecter Module ./connectors/postgresql not found, will try another candidate

### ISSUE THREAD

**Issue by akhudairyOP** [strongloop/loopback-connector-postgresql#452]
First of all my app is working, and connection is working. It is just that debug console is very confusing to me.

When I run my app "DEBUG=loopback:data* npm start" I see the following logs

  **loopback:datasource Module ./connectors/postgresql not found, will try another candidate. +1ms
  loopback:datasource Initializing connector undefined +286ms**
  loopback:datasource Datasource user: connected=false connecting=true +22ms
  loopback:datasource Connector is initialized for dataSource user +946ms
  **loopback:datasource DataSource user is now connected to postgresql +1ms**
  loopback:datasource Datasource user is now connected - executing method  +0ms
  loopback:datasource Datasource user: connected=true connecting=true +1ms
Server is running at http://[::1]:3000

I am using now "loopback-connector-postgresql": "^5.0.1", but I noticed the same logs on older versions also.

**Comment by ewrayjohnson** [comment]
I too am seeing this today, but not yesterday, after upgrading to NodeJS 14.7.0 from 12.18.3
