### ISSUE TITLE
#456 causes multiple major versions of loopback-connector

### ISSUE THREAD

**Issue by billinghamj** [strongloop/loopback-connector-postgresql#463]
Opening this issue as requested https://github.com/strongloop/loopback-connector-postgresql/pull/456#issuecomment-705098592

Following #456, the latest version of `loopback-connector-postgresql` refers to `loopback-connector` v5, but the latest version of `loopback-datasource-juggler` refers to `loopback-connector` v4, resulting in two different versions having to be installed at the same time.

It seems it's necessary to release a new version of `loopback-datasource-juggler` with updated dependencies to address this.

**Comment by dhmlau** [comment]
@bajtos, could you please take a look? Thanks.

**Comment by bajtos** [comment]
@billinghamj in https://github.com/strongloop/loopback-connector/pull/181#issuecomment-705093410, you wrote:

> it seems like a fairly big problem to have two incompatible versions running together?

As far as I know, it's fine to have multiple versions of the same module installed in the same project. In LoopBack, we go quite far to ensure our code is designed to handle multiple versions of the same module installed.

Is there any particular issue you are running into?

Having said that, I agree we should update `loopback-datasource-juggler` to use the latest version of `loopback-connector` too, I'll open a pull request soon.

**Comment by billinghamj** [comment]
No particular issue, just the concern that loopback is pretty fragile in our stack and I want to avoid the risk

Thanks for updating it! :)
