### ISSUE TITLE
Index implementation

### ISSUE THREAD

**Issue by grosem** [strongloop/loopback-connector-postgresql#47]
Index definitions are currently ignored. Can we adapt the implementation from the mysql connector?

Also, documentation (http://docs.strongloop.com/display/public/LB/Model+definition+JSON+file) should point out that this is not implemented for all connectors yet. I will create a separate documentation issue for that.

**Comment by ilianaza** [comment]
+1

**Comment by bananajohnny** [comment]
+1

**Comment by Klowner** [comment]
+1 for me as well, I've also started working on it https://github.com/Klowner/loopback-connector-postgresql/tree/feature/index-implementation

**Comment by eroh92** [comment]
+1
