### ISSUE TITLE
Use pgcrypto for user password.

### ISSUE THREAD

**Issue by aars** [strongloop/loopback-connector-postgresql#48]
I'd like to use Postgres' built-in pgcrypto to encyrpt/hash/check user credentials. Is this possible? As far as I can tell strongloop always hashes passwords before looking them up in the DB. I would like Postgres to handle that.

Is there maybe a method I could override where I can write my own SQL query?

Edit: I realize that this question is very much related to the default User model setup. I've skipped this "problem" for now and used the default methods provided by Strongloop. Will be modifying that in the future.

I would like to know/find out how I can write my own SQL queries in the future, or at least, use some of Postgres' specific features. The connection via jugglingdb seems very generic. I'm sure it's possible to find the DB connection via app.datasources['postgres-db'], but I'm not sure if it's a good idea.

**Comment by aars** [comment]
Figured this part out (the custom queries).

**Comment by titusfoo** [comment]
@aars would be good to know how did you end up implementing this considering #113
