### ISSUE TITLE
Getting error while creating new role over REST interface.

### ISSUE THREAD

**Issue by fusionstrings** [strongloop/loopback-connector-postgresql#5]
I am getting following error while trying to create a new role over REST interface, if I am not passing `id` manually. While manually passing id is saving the data. Which should not happen and id should be auto generated, unless I am missing here some thing..
   ` {
    -error: {
        name: "error"
        status: 500
        message: "null value in column "
        id " violates not-null constraint"
        length: 246
        severity: "ERROR"
        code: "23502"
        detail: "Failing row contains (null, adminjk, nj, 2014-05-14 00:18:20+05:30, 2014-05-14 00:18:20+05:30)."
        file: "src\backend\executor\execMain.c"
        line: "1611"
        routine: "ExecConstraints"
        stack: "error: null value in column "
        id " violates not-null constraint at Connection.parseE (E:\projects\Git\SourceTree\ConverBiz\SecondarySales\apiss\node_modules\loopback-connector-postgresql\node_modules\pg\lib\connection.js:521:11) at Connection.parseMessage (E:\projects\Git\SourceTree\ConverBiz\SecondarySales\apiss\node_modules\loopback-connector-postgresql\node_modules\pg\lib\connection.js:351:17) at Socket.<anonymous> (E:\projects\Git\SourceTree\ConverBiz\SecondarySales\apiss\node_modules\loopback-connector-postgresql\node_modules\pg\lib\connection.js:101:22) at Socket.EventEmitter.emit (events.js:95:17) at Socket.<anonymous> (_stream_readable.js:746:14) at Socket.EventEmitter.emit (events.js:92:17) at emitReadable_ (_stream_readable.js:408:10) at emitReadable (_stream_readable.js:404:5) at readableAddChunk (_stream_readable.js:165:9) at Socket.Readable.push (_stream_readable.js:127:10)"`

**Comment by davidcheung** [comment]
Cleaning up old issues, looks like fixed by strongloop/loopback#254, closing issue.
