### ISSUE TITLE
How to ONLY insert given properties and not send NULL to database.

### ISSUE THREAD

**Issue by aars** [strongloop/loopback-connector-postgresql#50]
I have a TIMESTAMP column named created in my users table. The database knows the default value for it, and I want the database to handle this.

How can I make sure that a Model.save() creates an SQL query that only inserts the properties I tell it to?

For example:

``` javascript
Access.create([{ // Extends User
  uuid: rID.uuid, // Some uuid I got from some other Model
  username: 'aaron',
  password: 'test',
  email: 'test@test.test'
}]);
```

Ends up trying to insert every column of the Model/Table.

``` sql
INSERT INTO "public"."access" ("uuid","name","username","password","role","acl","created","expired","realm","credentials","challenges","email","emailverified","verificationtoken","status","lastupdated")

Failing row contains (42, 0b81bb8b-1962-4b01-9f4c-87a0938bf94b, owner, null, aaron, $2a$10$GtfE7X4BR.eyf/AI7qwHQegYdqEaEzIFnLgMy5mqkc6JQ8bB6j3e2, {"all": "rw"}, null, null, null, null, null, test@test.test, null, null, null, null).
```

How can I prevent all these null values? I want (need) my database to handle default values. I know I can set the default values ALSO in my model definition, but I don't see why I should have to. This would also mean that a simple misconfigured timezone on an application server will mess up these Date fields, since the Default Value was decided on by my NodeJS Application and not in the database.

**Comment by raymondfeng** [comment]
One option is to skip columns that don't have corresponding values set in the data object during create(). For example, if data.role === undefined, we should not insert it.

**Comment by aars** [comment]
That is what I want yes! I'm not sure if you're telling me this is possible (via the create() method) or that you would implement it like this.

I tried manipulating data on beforeCreate and beforeSave, but the data those methods receive is the exact data I put into Access.create(). Should I look into the connector itself (or the Model/PersistedModel of loopback/strongloop?)

**Comment by raymondfeng** [comment]
Please check the connector implementations. Patches are welcome!

**Comment by aars** [comment]
Will do!

**Comment by aars** [comment]
@raymondfeng Check my PR. It might be a bit invasive, but I see no reason to add a switch/option for this behavior.

**Comment by 0candy** [comment]
@aars Does this PR https://github.com/strongloop/loopback-connector-postgresql/pull/54 resolve this issue?
