### ISSUE TITLE
Numeric is converted to String

### ISSUE THREAD

**Issue by bitmage** [strongloop/loopback-connector-postgresql#58]
With this in my model.json:

``` json
{
  "amount": {
    "type": "number",
    "human": "Amount",
    "postgresql": {
      "dataType": "numeric",
      "dataPrecision": 16,
      "dataScale": 4
    }
  }
}
```

When I store the value `50000.5413` I get back `'50000.5413'`.

**Comment by kelchm** [comment]
I'm also seeing this issue -- any update?

**Comment by mirow** [comment]
The problem (and solution) is here: 
https://github.com/brianc/node-pg-types/issues/28

**Comment by ssh24** [comment]
Added docs to allow the users know of this behaviour. Closing this issue.
