### ISSUE TITLE
Large arrays of integers

### ISSUE THREAD

**Issue by rubentorresbonet** [strongloop/loopback-connector-postgresql#60]
I tried storing large arrays but I received this error:

error: value too long for type character varying(1024)

For now, I manually set the column's type to text. Is this a safe workaround or will that information be lost whenever I migrate?
What is the suggested way of getting around this issue?

Thanks
Rubén

**Comment by rubentorresbonet** [comment]
A better workaround. Go to your model json and set in your property:

      "postgresql": {
        "dataType": "CHARACTER VARYING(2048)"
      }

or similar.

**Comment by vespertilian** [comment]
I was getting this error trying to store objects: 
Here was my solution:

"questions": {
      "type": [
        "object"
      ],
      "postgresql": {
        "columnName": "questions",
        "dataType": "json"
      },
      "required": true
    }

Storing my array of objects as a JSON datatype
