### ISSUE TITLE
Support for postgres uuid

### ISSUE THREAD

**Issue by vespertilian** [strongloop/loopback-connector-postgresql#61]
It would be great if the loopback connector supported the postgresql UUID datatype for better performance.  

http://simononsoftware.com/how-to-store-uuids-in-postgresql/

I tried to add it as a datatype but it gets set as numeric, when I think it should be mapped to a JS string.

**Comment by aol-nnov** [comment]
@vespertilian  please refer to #54 It will give you some glue on how to use postgresql uuid data type

**Comment by vespertilian** [comment]
Thanks 

@aol-nnov   

```
  "id": {
      "type": "string",
      "id": true,
      "required": false,
      "defaultFn": "uuid",
      "postgresql": {
        "dataType": "uuid"
      }
    },
    "name": {
      "type": "string",
      "required": true
    }

```
