### ISSUE TITLE
9.4 json column types

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-connector-postgresql#63]
are there any plans on supporting the new 9.4 data types (http://www.postgresql.org/docs/9.4/static/datatype-json.html) that can now be indexed and queried ?

**Comment by aol-nnov** [comment]
Hi, @jmls! Would you mind joining #59? I've started working on it lately, but have no spare time now to continue with the same pace...

**Comment by dhmlau** [comment]
@jmls, looks like you've joined the discussion in https://github.com/strongloop/loopback-connector-postgresql/pull/59.  Closing this one.
