### ISSUE TITLE
Recreate the database on `npm test` to allow parallel CI test execution

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-connector-postgresql#68]
As discussed with @rmg in Slack, current builds can't be run in parallel because we don't recreate the database when running `npm test`. It was suggested that running [`tables.sql`](https://github.com/strongloop/loopback-connector-postgresql/blob/master/test/tables.sql) before each `npm test` would be enough. Therefore the tasks are as follows:
1. Create a script to run `tables.sql`
2. Create `pretest` in the script section of `package.json` that runs the script in step 1 when `npm test` is executed.

**Comment by ssh24** [comment]
This should be the current behaviour of our CI. The current behaviour is:
- uses docker to spawn up a container
- run the `pretest` which seeds the database
- run the test (`npm test`)
- dispose the container

Closing this issue since it is done. Feel free to reopen if needed.
