### ISSUE TITLE
Add an example for connecting to UNIX domain socket

### ISSUE THREAD

**Issue by pmontrasio** [strongloop/loopback-connector-postgresql#72]
A common PostgreSQL configuration is to connect to the UNIX domain socket /var/run/postgresql/.s.PGSQL.5432 instead of using the TCP/IP port. I read the code and made some attempts at configuring datasources.json until I found the solution

    {
      "postgres": {
        "host": "/var/run/postgresql/",
        "port": "5432",
        "database": "dbname",
        "username": "dbuser",
        "password": "dbpassword",
        "name": "postgres",
        "debug": true,
        "connector": "postgresql"
      }
    }

I think this could be added to the README.

**Comment by raymondfeng** [comment]
@pmontrasio Thanks! 

@crandmck Can you update the docs?

**Comment by crandmck** [comment]
I copied the above to http://docs.strongloop.com/display/LB/PostgreSQL+connector#PostgreSQLconnector-ConnectingtoUNIXdomainsocket.  
@raymondfeng If that looks OK, I guess you can close this.
Thanks @pmontrasio

**Comment by pmontrasio** [comment]
That was quick!
Thanks @raymondfeng and @crandmck
