### ISSUE TITLE
geopoint保存到postgresql数据库中时有误

### ISSUE THREAD

**Issue by ltjin** [strongloop/loopback-connector-postgresql#73]
geopoint类型的数据保存到postgresql数据库中使用的为POINT类型，
格式为：POINT(39.908701 116.397482)，
实际上postgresql数据库的POINT类型格式是：POINT(116.397482 39.908701)。

错误的数据格式，在使用一下sql查询时出现异常：
SELECT st_distance(ST_Transform(ST_GeomFromText('POINT(39.908701 116.397482)',4326),26986), ST_Transform(ST_GeomFromText('POINT(39.908701 116.397482)',4326),26986));

ERROR:  transform: couldn't project point (39.9087 116.397 0): latitude or longitude exceeded limits (-14)

**Comment by 0candy** [comment]
Closing this issue as the fix was already merged.
