### ISSUE TITLE
Allow changing poolSize and poolIdleTimeout

### ISSUE THREAD

**Issue by mcouzinet** [strongloop/loopback-connector-postgresql#74]
Allow changing poolSize and poolIdleTimeout

**Comment by mcouzinet** [comment]
But seem correct with the futur connector refactor right ?

**Comment by ketansp** [comment]
Any updates?

**Comment by 0candy** [comment]
@mcouzinet Would you like to submit a patch?

**Comment by ssh24** [comment]
You can specify the `poolSize` and `poolIdleTimeout` as `max` and `idleTimeoutMillis`. Read more in the postgres driver [docs](https://github.com/brianc/node-postgres#pooling-example).

```js
var config = {
  user: 'foo', //env var: PGUSER
  database: 'my_db', //env var: PGDATABASE
  password: 'secret', //env var: PGPASSWORD
  host: 'localhost', // Server hosting the postgres database
  port: 5432, //env var: PGPORT
  max: 10, // max number of clients in the pool
  idleTimeoutMillis: 30000, // how long a client is allowed to remain idle before being closed
};
```

Closing this issue as resolved. Feel free to reopen if needed.
