### ISSUE TITLE
Feature request: ability to set connection settings

### ISSUE THREAD

**Issue by kesavkolla** [strongloop/loopback-connector-postgresql#76]
I've a requirement to change session settings.  The use case is I need to set timezone setting on pg client so that all timestamp with time zone data works properly.  Since this connector opens a new connection from pool every time I can't just set the session properties during boot time.

Basically I've to set the following session properties on connection before query executes.

SET SESSION TIME ZONE 'America/Los_Angeles'
SET SEARCH_PATH schema1, public

I think it's better to add a callback function for connection so application can decides what to do with the connection.

**Comment by 0candy** [comment]
@kesavkolla Would you like to submit a patch?
