### ISSUE TITLE
postgresql.OutParam is not a valid function

### ISSUE THREAD

**Issue by kesavkolla** [strongloop/loopback-connector-postgresql#8]
There is no OutParam defined in pg node module.  This is throwing error while create/update

**Comment by davidcheung** [comment]
Cleaning up old issues, https://github.com/strongloop/loopback-connector-postgresql/commit/502d873ddfa6e6c74a71ef70efc690a2f715ef50 Pulled in from PR #10 to fix this issue, closing issue.
