### ISSUE TITLE
trackChanges does not work with PostgreSQL

### ISSUE THREAD

**Issue by Nutelac** [strongloop/loopback-connector-postgresql#82]
When `trackChanges` is `true`, I got error:

```
error: relation "public.program-change" does not exist
    at [object Object].Connection.parseE (.../node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:534:11)
    at [object Object].Connection.parseMessage (.../node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (.../node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
```

When is `false` or with memory connector, everything works well.

**article.json:**

``` json
{
  "name": "Program",
  "base": "PersistedModel",
  "trackChanges": true,
  "options": {
    "postgresql": {
      "schema": "myschema",
      "table": "programs"
    }
  },
  "properties": {
    "id": {
      "id": true,
      "type": "string",
      "defaultFn": "guid",
      "postgresql": {
        "columnName": "id",
        "dataType": "text"
      }
    }
  }
}
```

Is there something that I missed?

**Comment by raymondfeng** [comment]
You need to create the database table manually or use ‘automigrate’. See:

http://docs.strongloop.com/display/LB/Creating+a+database+schema+from+models <http://docs.strongloop.com/display/LB/Creating+a+database+schema+from+models> 
http://docs.strongloop.com/display/APIS/Creating+and+editing+models#Creatingandeditingmodels-Migratingamodel <http://docs.strongloop.com/display/APIS/Creating+and+editing+models#Creatingandeditingmodels-Migratingamodel>


Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by Nutelac** [comment]
Thank you for reply. Unfortunately, I'm getting this error even while automigrating. No table is created.

**migrate.js**
```
import server from './server'

server.datasources['db'].automigrate(['Program'], (err) => console.log(err))
```

**Comment by Nutelac** [comment]
I found [Change](https://github.com/strongloop/loopback/blob/19a3fe64e45c083e998cdd65f8c31cc19d1cb807/common/models/change.json) model definition in `loopback/common/models` directory.  Should I create another model extending this?

**Comment by kaktus42** [comment]
I have that problem as well. @Nutelac 
Unfortunately your workaround did not work for me :(

Any news or ideas? @raymondfeng

**Comment by mivion** [comment]
Problem may be fixed by defining handleChangeError () on tracked model.
