### ISSUE TITLE
Error for the latest postgresql connector, method 'notifyObserversAround' does not exist(Bug)

### ISSUE THREAD

**Issue by mqslove17** [strongloop/loopback-connector-postgresql#84]
this.notifyObserversAround('execute', context, function(context, done) {
       ^
TypeError: Object #<PostgreSQL> has no method 'notifyObserversAround'
    at PostgreSQL.SQLConnector.execute (D:\Workspace\RockieData\Sandbox\MK\alert
\node_modules\loopback-connector-postgresql\node_modules\loopback-connector\lib\
sql.js:407:8)
    at DataSource.<anonymous> (D:\Workspace\RockieData\Sandbox\MK\alert\node_mod
ules\loopback-connector-postgresql\node_modules\loopback-connector\lib\sql.js:39
7:12)
    at DataSource.g (events.js:180:16)
    at DataSource.EventEmitter.emit (events.js:92:17)
    at DataSource.postInit (D:\Workspace\RockieData\Sandbox\MK\alert\node_module
s\loopback-datasource-juggler\lib\datasource.js:310:14)
    at D:\Workspace\RockieData\Sandbox\MK\alert\node_modules\loopback-connector-
postgresql\lib\postgresql.js:91:17
    at D:\Workspace\RockieData\Sandbox\MK\alert\node_modules\loopback-connector-
postgresql\node_modules\pg\lib\pool.js:77:9
    at D:\Workspace\RockieData\Sandbox\MK\alert\node_modules\loopback-connector-
postgresql\node_modules\pg\node_modules\generic-pool\lib\generic-pool.js:281:11
    at D:\Workspace\RockieData\Sandbox\MK\alert\node_modules\loopback-connector-
postgresql\node_modules\pg\lib\pool.js:51:18
    at null.<anonymous> (D:\Workspace\RockieData\Sandbox\MK\alert\node_modules\l
oopback-connector-postgresql\node_modules\pg\lib\client.js:144:7)

**Comment by mqslove17** [comment]
Issue exist in 2.1.0, checkout 1.7.1 could bypass this error.

**Comment by Neil-UWA** [comment]
@raymondfeng @mqslove17 , I had the same problem , event after I updated both loopback-connector-postgresql and loopback-connector-juggler.

**Comment by ssh24** [comment]
This issue should be fixed in the current version of the connector. Please make sure to have the updated version of `loopback-datasource-juggler` as well. Similar to https://github.com/strongloop/loopback-connector/issues/20

Closing this issue as resolved. Feel free to reopen if needed.
