### ISSUE TITLE
isActual always returning false, even after autoupdate

### ISSUE THREAD

**Issue by cooperjbrandon** [strongloop/loopback-connector-postgresql#94]
`isActual` method always returns false. To expand, i extended the base User model, adding `firstname`. I traced the problem down to the dataTypeChanged function, which always returns true for every string datatype (`username`, `password`, `email`, etc...).

This is due to this line: 
https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/migration.js#L221

Look at the `oldSettings` object, which comes from the `actualFields` parameter (which comes from these db query: https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/migration.js#L23-26). The `type` property of `oldSettings` for any string is `character varying`, but the `self.columnDataType` evalutes to `VARCHAR (1024)`, from this line: 
https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/migration.js#L466.

Essentially, `CHARACTER VARYING` will never equal `VARCHAR (1024)`, even after running autoupdate. Is there a work around for this?

I also notice there is the `postgresqlDataTypeToJSONType` function, but it isn't being used anywhere.

**Comment by cooperjbrandon** [comment]
resolved - see this commit: e04ab44f30d2f398c6ecec86fd51c8827918801a

**Comment by shSina** [comment]
double is not data type and cause this function to always return false , when we use double precision as data type.
